// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bookmark.proto

package GRPCService;

public final class BookmarkOuterClass {
  private BookmarkOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:bookmark.Message)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string string = 1;</code>
     */
    java.lang.String getString();
    /**
     * <code>string string = 1;</code>
     */
    com.google.protobuf.ByteString
        getStringBytes();
  }
  /**
   * Protobuf type {@code bookmark.Message}
   */
  public  static final class Message extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:bookmark.Message)
      MessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Message.newBuilder() to construct.
    private Message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Message() {
      string_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Message(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              string_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return GRPCService.BookmarkOuterClass.internal_static_bookmark_Message_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return GRPCService.BookmarkOuterClass.internal_static_bookmark_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              GRPCService.BookmarkOuterClass.Message.class, GRPCService.BookmarkOuterClass.Message.Builder.class);
    }

    public static final int STRING_FIELD_NUMBER = 1;
    private volatile java.lang.Object string_;
    /**
     * <code>string string = 1;</code>
     */
    public java.lang.String getString() {
      java.lang.Object ref = string_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        string_ = s;
        return s;
      }
    }
    /**
     * <code>string string = 1;</code>
     */
    public com.google.protobuf.ByteString
        getStringBytes() {
      java.lang.Object ref = string_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        string_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getStringBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, string_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getStringBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, string_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof GRPCService.BookmarkOuterClass.Message)) {
        return super.equals(obj);
      }
      GRPCService.BookmarkOuterClass.Message other = (GRPCService.BookmarkOuterClass.Message) obj;

      boolean result = true;
      result = result && getString()
          .equals(other.getString());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + STRING_FIELD_NUMBER;
      hash = (53 * hash) + getString().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static GRPCService.BookmarkOuterClass.Message parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GRPCService.BookmarkOuterClass.Message parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GRPCService.BookmarkOuterClass.Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GRPCService.BookmarkOuterClass.Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GRPCService.BookmarkOuterClass.Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GRPCService.BookmarkOuterClass.Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GRPCService.BookmarkOuterClass.Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GRPCService.BookmarkOuterClass.Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static GRPCService.BookmarkOuterClass.Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static GRPCService.BookmarkOuterClass.Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static GRPCService.BookmarkOuterClass.Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GRPCService.BookmarkOuterClass.Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(GRPCService.BookmarkOuterClass.Message prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code bookmark.Message}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:bookmark.Message)
        GRPCService.BookmarkOuterClass.MessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return GRPCService.BookmarkOuterClass.internal_static_bookmark_Message_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return GRPCService.BookmarkOuterClass.internal_static_bookmark_Message_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                GRPCService.BookmarkOuterClass.Message.class, GRPCService.BookmarkOuterClass.Message.Builder.class);
      }

      // Construct using GRPCService.BookmarkOuterClass.Message.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        string_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return GRPCService.BookmarkOuterClass.internal_static_bookmark_Message_descriptor;
      }

      @java.lang.Override
      public GRPCService.BookmarkOuterClass.Message getDefaultInstanceForType() {
        return GRPCService.BookmarkOuterClass.Message.getDefaultInstance();
      }

      @java.lang.Override
      public GRPCService.BookmarkOuterClass.Message build() {
        GRPCService.BookmarkOuterClass.Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public GRPCService.BookmarkOuterClass.Message buildPartial() {
        GRPCService.BookmarkOuterClass.Message result = new GRPCService.BookmarkOuterClass.Message(this);
        result.string_ = string_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof GRPCService.BookmarkOuterClass.Message) {
          return mergeFrom((GRPCService.BookmarkOuterClass.Message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(GRPCService.BookmarkOuterClass.Message other) {
        if (other == GRPCService.BookmarkOuterClass.Message.getDefaultInstance()) return this;
        if (!other.getString().isEmpty()) {
          string_ = other.string_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        GRPCService.BookmarkOuterClass.Message parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (GRPCService.BookmarkOuterClass.Message) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object string_ = "";
      /**
       * <code>string string = 1;</code>
       */
      public java.lang.String getString() {
        java.lang.Object ref = string_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          string_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string string = 1;</code>
       */
      public com.google.protobuf.ByteString
          getStringBytes() {
        java.lang.Object ref = string_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          string_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string string = 1;</code>
       */
      public Builder setString(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        string_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string string = 1;</code>
       */
      public Builder clearString() {
        
        string_ = getDefaultInstance().getString();
        onChanged();
        return this;
      }
      /**
       * <code>string string = 1;</code>
       */
      public Builder setStringBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        string_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:bookmark.Message)
    }

    // @@protoc_insertion_point(class_scope:bookmark.Message)
    private static final GRPCService.BookmarkOuterClass.Message DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new GRPCService.BookmarkOuterClass.Message();
    }

    public static GRPCService.BookmarkOuterClass.Message getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Message>
        PARSER = new com.google.protobuf.AbstractParser<Message>() {
      @java.lang.Override
      public Message parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Message(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Message> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Message> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public GRPCService.BookmarkOuterClass.Message getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface BookmarkObjOrBuilder extends
      // @@protoc_insertion_point(interface_extends:bookmark.BookmarkObj)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.user.UserObj User = 1;</code>
     */
    boolean hasUser();
    /**
     * <code>.user.UserObj User = 1;</code>
     */
    GRPCService.UserOuterClass.UserObj getUser();
    /**
     * <code>.user.UserObj User = 1;</code>
     */
    GRPCService.UserOuterClass.UserObjOrBuilder getUserOrBuilder();

    /**
     * <code>.post.PostObj Post = 2;</code>
     */
    boolean hasPost();
    /**
     * <code>.post.PostObj Post = 2;</code>
     */
    GRPCService.PostOuterClass.PostObj getPost();
    /**
     * <code>.post.PostObj Post = 2;</code>
     */
    GRPCService.PostOuterClass.PostObjOrBuilder getPostOrBuilder();
  }
  /**
   * Protobuf type {@code bookmark.BookmarkObj}
   */
  public  static final class BookmarkObj extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:bookmark.BookmarkObj)
      BookmarkObjOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BookmarkObj.newBuilder() to construct.
    private BookmarkObj(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BookmarkObj() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BookmarkObj(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              GRPCService.UserOuterClass.UserObj.Builder subBuilder = null;
              if (user_ != null) {
                subBuilder = user_.toBuilder();
              }
              user_ = input.readMessage(GRPCService.UserOuterClass.UserObj.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(user_);
                user_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              GRPCService.PostOuterClass.PostObj.Builder subBuilder = null;
              if (post_ != null) {
                subBuilder = post_.toBuilder();
              }
              post_ = input.readMessage(GRPCService.PostOuterClass.PostObj.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(post_);
                post_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return GRPCService.BookmarkOuterClass.internal_static_bookmark_BookmarkObj_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return GRPCService.BookmarkOuterClass.internal_static_bookmark_BookmarkObj_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              GRPCService.BookmarkOuterClass.BookmarkObj.class, GRPCService.BookmarkOuterClass.BookmarkObj.Builder.class);
    }

    public static final int USER_FIELD_NUMBER = 1;
    private GRPCService.UserOuterClass.UserObj user_;
    /**
     * <code>.user.UserObj User = 1;</code>
     */
    public boolean hasUser() {
      return user_ != null;
    }
    /**
     * <code>.user.UserObj User = 1;</code>
     */
    public GRPCService.UserOuterClass.UserObj getUser() {
      return user_ == null ? GRPCService.UserOuterClass.UserObj.getDefaultInstance() : user_;
    }
    /**
     * <code>.user.UserObj User = 1;</code>
     */
    public GRPCService.UserOuterClass.UserObjOrBuilder getUserOrBuilder() {
      return getUser();
    }

    public static final int POST_FIELD_NUMBER = 2;
    private GRPCService.PostOuterClass.PostObj post_;
    /**
     * <code>.post.PostObj Post = 2;</code>
     */
    public boolean hasPost() {
      return post_ != null;
    }
    /**
     * <code>.post.PostObj Post = 2;</code>
     */
    public GRPCService.PostOuterClass.PostObj getPost() {
      return post_ == null ? GRPCService.PostOuterClass.PostObj.getDefaultInstance() : post_;
    }
    /**
     * <code>.post.PostObj Post = 2;</code>
     */
    public GRPCService.PostOuterClass.PostObjOrBuilder getPostOrBuilder() {
      return getPost();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (user_ != null) {
        output.writeMessage(1, getUser());
      }
      if (post_ != null) {
        output.writeMessage(2, getPost());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (user_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getUser());
      }
      if (post_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getPost());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof GRPCService.BookmarkOuterClass.BookmarkObj)) {
        return super.equals(obj);
      }
      GRPCService.BookmarkOuterClass.BookmarkObj other = (GRPCService.BookmarkOuterClass.BookmarkObj) obj;

      boolean result = true;
      result = result && (hasUser() == other.hasUser());
      if (hasUser()) {
        result = result && getUser()
            .equals(other.getUser());
      }
      result = result && (hasPost() == other.hasPost());
      if (hasPost()) {
        result = result && getPost()
            .equals(other.getPost());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasUser()) {
        hash = (37 * hash) + USER_FIELD_NUMBER;
        hash = (53 * hash) + getUser().hashCode();
      }
      if (hasPost()) {
        hash = (37 * hash) + POST_FIELD_NUMBER;
        hash = (53 * hash) + getPost().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static GRPCService.BookmarkOuterClass.BookmarkObj parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GRPCService.BookmarkOuterClass.BookmarkObj parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GRPCService.BookmarkOuterClass.BookmarkObj parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GRPCService.BookmarkOuterClass.BookmarkObj parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GRPCService.BookmarkOuterClass.BookmarkObj parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GRPCService.BookmarkOuterClass.BookmarkObj parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GRPCService.BookmarkOuterClass.BookmarkObj parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GRPCService.BookmarkOuterClass.BookmarkObj parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static GRPCService.BookmarkOuterClass.BookmarkObj parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static GRPCService.BookmarkOuterClass.BookmarkObj parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static GRPCService.BookmarkOuterClass.BookmarkObj parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GRPCService.BookmarkOuterClass.BookmarkObj parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(GRPCService.BookmarkOuterClass.BookmarkObj prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code bookmark.BookmarkObj}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:bookmark.BookmarkObj)
        GRPCService.BookmarkOuterClass.BookmarkObjOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return GRPCService.BookmarkOuterClass.internal_static_bookmark_BookmarkObj_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return GRPCService.BookmarkOuterClass.internal_static_bookmark_BookmarkObj_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                GRPCService.BookmarkOuterClass.BookmarkObj.class, GRPCService.BookmarkOuterClass.BookmarkObj.Builder.class);
      }

      // Construct using GRPCService.BookmarkOuterClass.BookmarkObj.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (userBuilder_ == null) {
          user_ = null;
        } else {
          user_ = null;
          userBuilder_ = null;
        }
        if (postBuilder_ == null) {
          post_ = null;
        } else {
          post_ = null;
          postBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return GRPCService.BookmarkOuterClass.internal_static_bookmark_BookmarkObj_descriptor;
      }

      @java.lang.Override
      public GRPCService.BookmarkOuterClass.BookmarkObj getDefaultInstanceForType() {
        return GRPCService.BookmarkOuterClass.BookmarkObj.getDefaultInstance();
      }

      @java.lang.Override
      public GRPCService.BookmarkOuterClass.BookmarkObj build() {
        GRPCService.BookmarkOuterClass.BookmarkObj result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public GRPCService.BookmarkOuterClass.BookmarkObj buildPartial() {
        GRPCService.BookmarkOuterClass.BookmarkObj result = new GRPCService.BookmarkOuterClass.BookmarkObj(this);
        if (userBuilder_ == null) {
          result.user_ = user_;
        } else {
          result.user_ = userBuilder_.build();
        }
        if (postBuilder_ == null) {
          result.post_ = post_;
        } else {
          result.post_ = postBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof GRPCService.BookmarkOuterClass.BookmarkObj) {
          return mergeFrom((GRPCService.BookmarkOuterClass.BookmarkObj)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(GRPCService.BookmarkOuterClass.BookmarkObj other) {
        if (other == GRPCService.BookmarkOuterClass.BookmarkObj.getDefaultInstance()) return this;
        if (other.hasUser()) {
          mergeUser(other.getUser());
        }
        if (other.hasPost()) {
          mergePost(other.getPost());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        GRPCService.BookmarkOuterClass.BookmarkObj parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (GRPCService.BookmarkOuterClass.BookmarkObj) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private GRPCService.UserOuterClass.UserObj user_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          GRPCService.UserOuterClass.UserObj, GRPCService.UserOuterClass.UserObj.Builder, GRPCService.UserOuterClass.UserObjOrBuilder> userBuilder_;
      /**
       * <code>.user.UserObj User = 1;</code>
       */
      public boolean hasUser() {
        return userBuilder_ != null || user_ != null;
      }
      /**
       * <code>.user.UserObj User = 1;</code>
       */
      public GRPCService.UserOuterClass.UserObj getUser() {
        if (userBuilder_ == null) {
          return user_ == null ? GRPCService.UserOuterClass.UserObj.getDefaultInstance() : user_;
        } else {
          return userBuilder_.getMessage();
        }
      }
      /**
       * <code>.user.UserObj User = 1;</code>
       */
      public Builder setUser(GRPCService.UserOuterClass.UserObj value) {
        if (userBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          user_ = value;
          onChanged();
        } else {
          userBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.user.UserObj User = 1;</code>
       */
      public Builder setUser(
          GRPCService.UserOuterClass.UserObj.Builder builderForValue) {
        if (userBuilder_ == null) {
          user_ = builderForValue.build();
          onChanged();
        } else {
          userBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.user.UserObj User = 1;</code>
       */
      public Builder mergeUser(GRPCService.UserOuterClass.UserObj value) {
        if (userBuilder_ == null) {
          if (user_ != null) {
            user_ =
              GRPCService.UserOuterClass.UserObj.newBuilder(user_).mergeFrom(value).buildPartial();
          } else {
            user_ = value;
          }
          onChanged();
        } else {
          userBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.user.UserObj User = 1;</code>
       */
      public Builder clearUser() {
        if (userBuilder_ == null) {
          user_ = null;
          onChanged();
        } else {
          user_ = null;
          userBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.user.UserObj User = 1;</code>
       */
      public GRPCService.UserOuterClass.UserObj.Builder getUserBuilder() {
        
        onChanged();
        return getUserFieldBuilder().getBuilder();
      }
      /**
       * <code>.user.UserObj User = 1;</code>
       */
      public GRPCService.UserOuterClass.UserObjOrBuilder getUserOrBuilder() {
        if (userBuilder_ != null) {
          return userBuilder_.getMessageOrBuilder();
        } else {
          return user_ == null ?
              GRPCService.UserOuterClass.UserObj.getDefaultInstance() : user_;
        }
      }
      /**
       * <code>.user.UserObj User = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          GRPCService.UserOuterClass.UserObj, GRPCService.UserOuterClass.UserObj.Builder, GRPCService.UserOuterClass.UserObjOrBuilder> 
          getUserFieldBuilder() {
        if (userBuilder_ == null) {
          userBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              GRPCService.UserOuterClass.UserObj, GRPCService.UserOuterClass.UserObj.Builder, GRPCService.UserOuterClass.UserObjOrBuilder>(
                  getUser(),
                  getParentForChildren(),
                  isClean());
          user_ = null;
        }
        return userBuilder_;
      }

      private GRPCService.PostOuterClass.PostObj post_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          GRPCService.PostOuterClass.PostObj, GRPCService.PostOuterClass.PostObj.Builder, GRPCService.PostOuterClass.PostObjOrBuilder> postBuilder_;
      /**
       * <code>.post.PostObj Post = 2;</code>
       */
      public boolean hasPost() {
        return postBuilder_ != null || post_ != null;
      }
      /**
       * <code>.post.PostObj Post = 2;</code>
       */
      public GRPCService.PostOuterClass.PostObj getPost() {
        if (postBuilder_ == null) {
          return post_ == null ? GRPCService.PostOuterClass.PostObj.getDefaultInstance() : post_;
        } else {
          return postBuilder_.getMessage();
        }
      }
      /**
       * <code>.post.PostObj Post = 2;</code>
       */
      public Builder setPost(GRPCService.PostOuterClass.PostObj value) {
        if (postBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          post_ = value;
          onChanged();
        } else {
          postBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.post.PostObj Post = 2;</code>
       */
      public Builder setPost(
          GRPCService.PostOuterClass.PostObj.Builder builderForValue) {
        if (postBuilder_ == null) {
          post_ = builderForValue.build();
          onChanged();
        } else {
          postBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.post.PostObj Post = 2;</code>
       */
      public Builder mergePost(GRPCService.PostOuterClass.PostObj value) {
        if (postBuilder_ == null) {
          if (post_ != null) {
            post_ =
              GRPCService.PostOuterClass.PostObj.newBuilder(post_).mergeFrom(value).buildPartial();
          } else {
            post_ = value;
          }
          onChanged();
        } else {
          postBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.post.PostObj Post = 2;</code>
       */
      public Builder clearPost() {
        if (postBuilder_ == null) {
          post_ = null;
          onChanged();
        } else {
          post_ = null;
          postBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.post.PostObj Post = 2;</code>
       */
      public GRPCService.PostOuterClass.PostObj.Builder getPostBuilder() {
        
        onChanged();
        return getPostFieldBuilder().getBuilder();
      }
      /**
       * <code>.post.PostObj Post = 2;</code>
       */
      public GRPCService.PostOuterClass.PostObjOrBuilder getPostOrBuilder() {
        if (postBuilder_ != null) {
          return postBuilder_.getMessageOrBuilder();
        } else {
          return post_ == null ?
              GRPCService.PostOuterClass.PostObj.getDefaultInstance() : post_;
        }
      }
      /**
       * <code>.post.PostObj Post = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          GRPCService.PostOuterClass.PostObj, GRPCService.PostOuterClass.PostObj.Builder, GRPCService.PostOuterClass.PostObjOrBuilder> 
          getPostFieldBuilder() {
        if (postBuilder_ == null) {
          postBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              GRPCService.PostOuterClass.PostObj, GRPCService.PostOuterClass.PostObj.Builder, GRPCService.PostOuterClass.PostObjOrBuilder>(
                  getPost(),
                  getParentForChildren(),
                  isClean());
          post_ = null;
        }
        return postBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:bookmark.BookmarkObj)
    }

    // @@protoc_insertion_point(class_scope:bookmark.BookmarkObj)
    private static final GRPCService.BookmarkOuterClass.BookmarkObj DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new GRPCService.BookmarkOuterClass.BookmarkObj();
    }

    public static GRPCService.BookmarkOuterClass.BookmarkObj getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BookmarkObj>
        PARSER = new com.google.protobuf.AbstractParser<BookmarkObj>() {
      @java.lang.Override
      public BookmarkObj parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BookmarkObj(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BookmarkObj> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BookmarkObj> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public GRPCService.BookmarkOuterClass.BookmarkObj getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface StringAndIntegerOrBuilder extends
      // @@protoc_insertion_point(interface_extends:bookmark.StringAndInteger)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 postId = 1;</code>
     */
    int getPostId();

    /**
     * <code>string userName = 2;</code>
     */
    java.lang.String getUserName();
    /**
     * <code>string userName = 2;</code>
     */
    com.google.protobuf.ByteString
        getUserNameBytes();
  }
  /**
   * Protobuf type {@code bookmark.StringAndInteger}
   */
  public  static final class StringAndInteger extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:bookmark.StringAndInteger)
      StringAndIntegerOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use StringAndInteger.newBuilder() to construct.
    private StringAndInteger(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private StringAndInteger() {
      postId_ = 0;
      userName_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private StringAndInteger(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              postId_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              userName_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return GRPCService.BookmarkOuterClass.internal_static_bookmark_StringAndInteger_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return GRPCService.BookmarkOuterClass.internal_static_bookmark_StringAndInteger_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              GRPCService.BookmarkOuterClass.StringAndInteger.class, GRPCService.BookmarkOuterClass.StringAndInteger.Builder.class);
    }

    public static final int POSTID_FIELD_NUMBER = 1;
    private int postId_;
    /**
     * <code>int32 postId = 1;</code>
     */
    public int getPostId() {
      return postId_;
    }

    public static final int USERNAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object userName_;
    /**
     * <code>string userName = 2;</code>
     */
    public java.lang.String getUserName() {
      java.lang.Object ref = userName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userName_ = s;
        return s;
      }
    }
    /**
     * <code>string userName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getUserNameBytes() {
      java.lang.Object ref = userName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (postId_ != 0) {
        output.writeInt32(1, postId_);
      }
      if (!getUserNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, userName_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (postId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, postId_);
      }
      if (!getUserNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, userName_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof GRPCService.BookmarkOuterClass.StringAndInteger)) {
        return super.equals(obj);
      }
      GRPCService.BookmarkOuterClass.StringAndInteger other = (GRPCService.BookmarkOuterClass.StringAndInteger) obj;

      boolean result = true;
      result = result && (getPostId()
          == other.getPostId());
      result = result && getUserName()
          .equals(other.getUserName());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + POSTID_FIELD_NUMBER;
      hash = (53 * hash) + getPostId();
      hash = (37 * hash) + USERNAME_FIELD_NUMBER;
      hash = (53 * hash) + getUserName().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static GRPCService.BookmarkOuterClass.StringAndInteger parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GRPCService.BookmarkOuterClass.StringAndInteger parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GRPCService.BookmarkOuterClass.StringAndInteger parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GRPCService.BookmarkOuterClass.StringAndInteger parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GRPCService.BookmarkOuterClass.StringAndInteger parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GRPCService.BookmarkOuterClass.StringAndInteger parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GRPCService.BookmarkOuterClass.StringAndInteger parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GRPCService.BookmarkOuterClass.StringAndInteger parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static GRPCService.BookmarkOuterClass.StringAndInteger parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static GRPCService.BookmarkOuterClass.StringAndInteger parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static GRPCService.BookmarkOuterClass.StringAndInteger parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GRPCService.BookmarkOuterClass.StringAndInteger parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(GRPCService.BookmarkOuterClass.StringAndInteger prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code bookmark.StringAndInteger}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:bookmark.StringAndInteger)
        GRPCService.BookmarkOuterClass.StringAndIntegerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return GRPCService.BookmarkOuterClass.internal_static_bookmark_StringAndInteger_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return GRPCService.BookmarkOuterClass.internal_static_bookmark_StringAndInteger_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                GRPCService.BookmarkOuterClass.StringAndInteger.class, GRPCService.BookmarkOuterClass.StringAndInteger.Builder.class);
      }

      // Construct using GRPCService.BookmarkOuterClass.StringAndInteger.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        postId_ = 0;

        userName_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return GRPCService.BookmarkOuterClass.internal_static_bookmark_StringAndInteger_descriptor;
      }

      @java.lang.Override
      public GRPCService.BookmarkOuterClass.StringAndInteger getDefaultInstanceForType() {
        return GRPCService.BookmarkOuterClass.StringAndInteger.getDefaultInstance();
      }

      @java.lang.Override
      public GRPCService.BookmarkOuterClass.StringAndInteger build() {
        GRPCService.BookmarkOuterClass.StringAndInteger result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public GRPCService.BookmarkOuterClass.StringAndInteger buildPartial() {
        GRPCService.BookmarkOuterClass.StringAndInteger result = new GRPCService.BookmarkOuterClass.StringAndInteger(this);
        result.postId_ = postId_;
        result.userName_ = userName_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof GRPCService.BookmarkOuterClass.StringAndInteger) {
          return mergeFrom((GRPCService.BookmarkOuterClass.StringAndInteger)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(GRPCService.BookmarkOuterClass.StringAndInteger other) {
        if (other == GRPCService.BookmarkOuterClass.StringAndInteger.getDefaultInstance()) return this;
        if (other.getPostId() != 0) {
          setPostId(other.getPostId());
        }
        if (!other.getUserName().isEmpty()) {
          userName_ = other.userName_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        GRPCService.BookmarkOuterClass.StringAndInteger parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (GRPCService.BookmarkOuterClass.StringAndInteger) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int postId_ ;
      /**
       * <code>int32 postId = 1;</code>
       */
      public int getPostId() {
        return postId_;
      }
      /**
       * <code>int32 postId = 1;</code>
       */
      public Builder setPostId(int value) {
        
        postId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 postId = 1;</code>
       */
      public Builder clearPostId() {
        
        postId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object userName_ = "";
      /**
       * <code>string userName = 2;</code>
       */
      public java.lang.String getUserName() {
        java.lang.Object ref = userName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string userName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getUserNameBytes() {
        java.lang.Object ref = userName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string userName = 2;</code>
       */
      public Builder setUserName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string userName = 2;</code>
       */
      public Builder clearUserName() {
        
        userName_ = getDefaultInstance().getUserName();
        onChanged();
        return this;
      }
      /**
       * <code>string userName = 2;</code>
       */
      public Builder setUserNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userName_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:bookmark.StringAndInteger)
    }

    // @@protoc_insertion_point(class_scope:bookmark.StringAndInteger)
    private static final GRPCService.BookmarkOuterClass.StringAndInteger DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new GRPCService.BookmarkOuterClass.StringAndInteger();
    }

    public static GRPCService.BookmarkOuterClass.StringAndInteger getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<StringAndInteger>
        PARSER = new com.google.protobuf.AbstractParser<StringAndInteger>() {
      @java.lang.Override
      public StringAndInteger parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new StringAndInteger(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<StringAndInteger> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<StringAndInteger> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public GRPCService.BookmarkOuterClass.StringAndInteger getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bookmark_Message_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bookmark_Message_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bookmark_BookmarkObj_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bookmark_BookmarkObj_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bookmark_StringAndInteger_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bookmark_StringAndInteger_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016bookmark.proto\022\010bookmark\032\nuser.proto\032\n" +
      "post.proto\"\031\n\007Message\022\016\n\006string\030\001 \001(\t\"G\n" +
      "\013BookmarkObj\022\033\n\004User\030\001 \001(\0132\r.user.UserOb" +
      "j\022\033\n\004Post\030\002 \001(\0132\r.post.PostObj\"4\n\020String" +
      "AndInteger\022\016\n\006postId\030\001 \001(\005\022\020\n\010userName\030\002" +
      " \001(\t2\203\001\n\010Bookmark\0226\n\nAddBoomark\022\025.bookma" +
      "rk.BookmarkObj\032\021.bookmark.Message\022?\n\016Rem" +
      "oveBookmark\022\032.bookmark.StringAndInteger\032" +
      "\021.bookmark.MessageB\r\n\013GRPCServiceb\006proto" +
      "3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          GRPCService.UserOuterClass.getDescriptor(),
          GRPCService.PostOuterClass.getDescriptor(),
        }, assigner);
    internal_static_bookmark_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_bookmark_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bookmark_Message_descriptor,
        new java.lang.String[] { "String", });
    internal_static_bookmark_BookmarkObj_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_bookmark_BookmarkObj_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bookmark_BookmarkObj_descriptor,
        new java.lang.String[] { "User", "Post", });
    internal_static_bookmark_StringAndInteger_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_bookmark_StringAndInteger_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bookmark_StringAndInteger_descriptor,
        new java.lang.String[] { "PostId", "UserName", });
    GRPCService.UserOuterClass.getDescriptor();
    GRPCService.PostOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
