// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: category.proto

package GRPCService;

public final class CategoryOuterClass {
  private CategoryOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CategoryObjOrBuilder extends
      // @@protoc_insertion_point(interface_extends:category.CategoryObj)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>repeated .subcategory.SubcategoryObj subCategories = 3;</code>
     */
    java.util.List<GRPCService.Subcategory.SubcategoryObj> 
        getSubCategoriesList();
    /**
     * <code>repeated .subcategory.SubcategoryObj subCategories = 3;</code>
     */
    GRPCService.Subcategory.SubcategoryObj getSubCategories(int index);
    /**
     * <code>repeated .subcategory.SubcategoryObj subCategories = 3;</code>
     */
    int getSubCategoriesCount();
    /**
     * <code>repeated .subcategory.SubcategoryObj subCategories = 3;</code>
     */
    java.util.List<? extends GRPCService.Subcategory.SubcategoryObjOrBuilder> 
        getSubCategoriesOrBuilderList();
    /**
     * <code>repeated .subcategory.SubcategoryObj subCategories = 3;</code>
     */
    GRPCService.Subcategory.SubcategoryObjOrBuilder getSubCategoriesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code category.CategoryObj}
   */
  public  static final class CategoryObj extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:category.CategoryObj)
      CategoryObjOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CategoryObj.newBuilder() to construct.
    private CategoryObj(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CategoryObj() {
      id_ = 0;
      name_ = "";
      subCategories_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CategoryObj(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                subCategories_ = new java.util.ArrayList<GRPCService.Subcategory.SubcategoryObj>();
                mutable_bitField0_ |= 0x00000004;
              }
              subCategories_.add(
                  input.readMessage(GRPCService.Subcategory.SubcategoryObj.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          subCategories_ = java.util.Collections.unmodifiableList(subCategories_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return GRPCService.CategoryOuterClass.internal_static_category_CategoryObj_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return GRPCService.CategoryOuterClass.internal_static_category_CategoryObj_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              GRPCService.CategoryOuterClass.CategoryObj.class, GRPCService.CategoryOuterClass.CategoryObj.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SUBCATEGORIES_FIELD_NUMBER = 3;
    private java.util.List<GRPCService.Subcategory.SubcategoryObj> subCategories_;
    /**
     * <code>repeated .subcategory.SubcategoryObj subCategories = 3;</code>
     */
    public java.util.List<GRPCService.Subcategory.SubcategoryObj> getSubCategoriesList() {
      return subCategories_;
    }
    /**
     * <code>repeated .subcategory.SubcategoryObj subCategories = 3;</code>
     */
    public java.util.List<? extends GRPCService.Subcategory.SubcategoryObjOrBuilder> 
        getSubCategoriesOrBuilderList() {
      return subCategories_;
    }
    /**
     * <code>repeated .subcategory.SubcategoryObj subCategories = 3;</code>
     */
    public int getSubCategoriesCount() {
      return subCategories_.size();
    }
    /**
     * <code>repeated .subcategory.SubcategoryObj subCategories = 3;</code>
     */
    public GRPCService.Subcategory.SubcategoryObj getSubCategories(int index) {
      return subCategories_.get(index);
    }
    /**
     * <code>repeated .subcategory.SubcategoryObj subCategories = 3;</code>
     */
    public GRPCService.Subcategory.SubcategoryObjOrBuilder getSubCategoriesOrBuilder(
        int index) {
      return subCategories_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      for (int i = 0; i < subCategories_.size(); i++) {
        output.writeMessage(3, subCategories_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      for (int i = 0; i < subCategories_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, subCategories_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof GRPCService.CategoryOuterClass.CategoryObj)) {
        return super.equals(obj);
      }
      GRPCService.CategoryOuterClass.CategoryObj other = (GRPCService.CategoryOuterClass.CategoryObj) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && getName()
          .equals(other.getName());
      result = result && getSubCategoriesList()
          .equals(other.getSubCategoriesList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      if (getSubCategoriesCount() > 0) {
        hash = (37 * hash) + SUBCATEGORIES_FIELD_NUMBER;
        hash = (53 * hash) + getSubCategoriesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static GRPCService.CategoryOuterClass.CategoryObj parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GRPCService.CategoryOuterClass.CategoryObj parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GRPCService.CategoryOuterClass.CategoryObj parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GRPCService.CategoryOuterClass.CategoryObj parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GRPCService.CategoryOuterClass.CategoryObj parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GRPCService.CategoryOuterClass.CategoryObj parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GRPCService.CategoryOuterClass.CategoryObj parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GRPCService.CategoryOuterClass.CategoryObj parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static GRPCService.CategoryOuterClass.CategoryObj parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static GRPCService.CategoryOuterClass.CategoryObj parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static GRPCService.CategoryOuterClass.CategoryObj parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GRPCService.CategoryOuterClass.CategoryObj parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(GRPCService.CategoryOuterClass.CategoryObj prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code category.CategoryObj}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:category.CategoryObj)
        GRPCService.CategoryOuterClass.CategoryObjOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return GRPCService.CategoryOuterClass.internal_static_category_CategoryObj_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return GRPCService.CategoryOuterClass.internal_static_category_CategoryObj_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                GRPCService.CategoryOuterClass.CategoryObj.class, GRPCService.CategoryOuterClass.CategoryObj.Builder.class);
      }

      // Construct using GRPCService.CategoryOuterClass.CategoryObj.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getSubCategoriesFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        name_ = "";

        if (subCategoriesBuilder_ == null) {
          subCategories_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          subCategoriesBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return GRPCService.CategoryOuterClass.internal_static_category_CategoryObj_descriptor;
      }

      @java.lang.Override
      public GRPCService.CategoryOuterClass.CategoryObj getDefaultInstanceForType() {
        return GRPCService.CategoryOuterClass.CategoryObj.getDefaultInstance();
      }

      @java.lang.Override
      public GRPCService.CategoryOuterClass.CategoryObj build() {
        GRPCService.CategoryOuterClass.CategoryObj result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public GRPCService.CategoryOuterClass.CategoryObj buildPartial() {
        GRPCService.CategoryOuterClass.CategoryObj result = new GRPCService.CategoryOuterClass.CategoryObj(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.id_ = id_;
        result.name_ = name_;
        if (subCategoriesBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            subCategories_ = java.util.Collections.unmodifiableList(subCategories_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.subCategories_ = subCategories_;
        } else {
          result.subCategories_ = subCategoriesBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof GRPCService.CategoryOuterClass.CategoryObj) {
          return mergeFrom((GRPCService.CategoryOuterClass.CategoryObj)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(GRPCService.CategoryOuterClass.CategoryObj other) {
        if (other == GRPCService.CategoryOuterClass.CategoryObj.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (subCategoriesBuilder_ == null) {
          if (!other.subCategories_.isEmpty()) {
            if (subCategories_.isEmpty()) {
              subCategories_ = other.subCategories_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureSubCategoriesIsMutable();
              subCategories_.addAll(other.subCategories_);
            }
            onChanged();
          }
        } else {
          if (!other.subCategories_.isEmpty()) {
            if (subCategoriesBuilder_.isEmpty()) {
              subCategoriesBuilder_.dispose();
              subCategoriesBuilder_ = null;
              subCategories_ = other.subCategories_;
              bitField0_ = (bitField0_ & ~0x00000004);
              subCategoriesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getSubCategoriesFieldBuilder() : null;
            } else {
              subCategoriesBuilder_.addAllMessages(other.subCategories_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        GRPCService.CategoryOuterClass.CategoryObj parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (GRPCService.CategoryOuterClass.CategoryObj) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.util.List<GRPCService.Subcategory.SubcategoryObj> subCategories_ =
        java.util.Collections.emptyList();
      private void ensureSubCategoriesIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          subCategories_ = new java.util.ArrayList<GRPCService.Subcategory.SubcategoryObj>(subCategories_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          GRPCService.Subcategory.SubcategoryObj, GRPCService.Subcategory.SubcategoryObj.Builder, GRPCService.Subcategory.SubcategoryObjOrBuilder> subCategoriesBuilder_;

      /**
       * <code>repeated .subcategory.SubcategoryObj subCategories = 3;</code>
       */
      public java.util.List<GRPCService.Subcategory.SubcategoryObj> getSubCategoriesList() {
        if (subCategoriesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(subCategories_);
        } else {
          return subCategoriesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .subcategory.SubcategoryObj subCategories = 3;</code>
       */
      public int getSubCategoriesCount() {
        if (subCategoriesBuilder_ == null) {
          return subCategories_.size();
        } else {
          return subCategoriesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .subcategory.SubcategoryObj subCategories = 3;</code>
       */
      public GRPCService.Subcategory.SubcategoryObj getSubCategories(int index) {
        if (subCategoriesBuilder_ == null) {
          return subCategories_.get(index);
        } else {
          return subCategoriesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .subcategory.SubcategoryObj subCategories = 3;</code>
       */
      public Builder setSubCategories(
          int index, GRPCService.Subcategory.SubcategoryObj value) {
        if (subCategoriesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSubCategoriesIsMutable();
          subCategories_.set(index, value);
          onChanged();
        } else {
          subCategoriesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .subcategory.SubcategoryObj subCategories = 3;</code>
       */
      public Builder setSubCategories(
          int index, GRPCService.Subcategory.SubcategoryObj.Builder builderForValue) {
        if (subCategoriesBuilder_ == null) {
          ensureSubCategoriesIsMutable();
          subCategories_.set(index, builderForValue.build());
          onChanged();
        } else {
          subCategoriesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .subcategory.SubcategoryObj subCategories = 3;</code>
       */
      public Builder addSubCategories(GRPCService.Subcategory.SubcategoryObj value) {
        if (subCategoriesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSubCategoriesIsMutable();
          subCategories_.add(value);
          onChanged();
        } else {
          subCategoriesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .subcategory.SubcategoryObj subCategories = 3;</code>
       */
      public Builder addSubCategories(
          int index, GRPCService.Subcategory.SubcategoryObj value) {
        if (subCategoriesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSubCategoriesIsMutable();
          subCategories_.add(index, value);
          onChanged();
        } else {
          subCategoriesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .subcategory.SubcategoryObj subCategories = 3;</code>
       */
      public Builder addSubCategories(
          GRPCService.Subcategory.SubcategoryObj.Builder builderForValue) {
        if (subCategoriesBuilder_ == null) {
          ensureSubCategoriesIsMutable();
          subCategories_.add(builderForValue.build());
          onChanged();
        } else {
          subCategoriesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .subcategory.SubcategoryObj subCategories = 3;</code>
       */
      public Builder addSubCategories(
          int index, GRPCService.Subcategory.SubcategoryObj.Builder builderForValue) {
        if (subCategoriesBuilder_ == null) {
          ensureSubCategoriesIsMutable();
          subCategories_.add(index, builderForValue.build());
          onChanged();
        } else {
          subCategoriesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .subcategory.SubcategoryObj subCategories = 3;</code>
       */
      public Builder addAllSubCategories(
          java.lang.Iterable<? extends GRPCService.Subcategory.SubcategoryObj> values) {
        if (subCategoriesBuilder_ == null) {
          ensureSubCategoriesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, subCategories_);
          onChanged();
        } else {
          subCategoriesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .subcategory.SubcategoryObj subCategories = 3;</code>
       */
      public Builder clearSubCategories() {
        if (subCategoriesBuilder_ == null) {
          subCategories_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          subCategoriesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .subcategory.SubcategoryObj subCategories = 3;</code>
       */
      public Builder removeSubCategories(int index) {
        if (subCategoriesBuilder_ == null) {
          ensureSubCategoriesIsMutable();
          subCategories_.remove(index);
          onChanged();
        } else {
          subCategoriesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .subcategory.SubcategoryObj subCategories = 3;</code>
       */
      public GRPCService.Subcategory.SubcategoryObj.Builder getSubCategoriesBuilder(
          int index) {
        return getSubCategoriesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .subcategory.SubcategoryObj subCategories = 3;</code>
       */
      public GRPCService.Subcategory.SubcategoryObjOrBuilder getSubCategoriesOrBuilder(
          int index) {
        if (subCategoriesBuilder_ == null) {
          return subCategories_.get(index);  } else {
          return subCategoriesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .subcategory.SubcategoryObj subCategories = 3;</code>
       */
      public java.util.List<? extends GRPCService.Subcategory.SubcategoryObjOrBuilder> 
           getSubCategoriesOrBuilderList() {
        if (subCategoriesBuilder_ != null) {
          return subCategoriesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(subCategories_);
        }
      }
      /**
       * <code>repeated .subcategory.SubcategoryObj subCategories = 3;</code>
       */
      public GRPCService.Subcategory.SubcategoryObj.Builder addSubCategoriesBuilder() {
        return getSubCategoriesFieldBuilder().addBuilder(
            GRPCService.Subcategory.SubcategoryObj.getDefaultInstance());
      }
      /**
       * <code>repeated .subcategory.SubcategoryObj subCategories = 3;</code>
       */
      public GRPCService.Subcategory.SubcategoryObj.Builder addSubCategoriesBuilder(
          int index) {
        return getSubCategoriesFieldBuilder().addBuilder(
            index, GRPCService.Subcategory.SubcategoryObj.getDefaultInstance());
      }
      /**
       * <code>repeated .subcategory.SubcategoryObj subCategories = 3;</code>
       */
      public java.util.List<GRPCService.Subcategory.SubcategoryObj.Builder> 
           getSubCategoriesBuilderList() {
        return getSubCategoriesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          GRPCService.Subcategory.SubcategoryObj, GRPCService.Subcategory.SubcategoryObj.Builder, GRPCService.Subcategory.SubcategoryObjOrBuilder> 
          getSubCategoriesFieldBuilder() {
        if (subCategoriesBuilder_ == null) {
          subCategoriesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              GRPCService.Subcategory.SubcategoryObj, GRPCService.Subcategory.SubcategoryObj.Builder, GRPCService.Subcategory.SubcategoryObjOrBuilder>(
                  subCategories_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          subCategories_ = null;
        }
        return subCategoriesBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:category.CategoryObj)
    }

    // @@protoc_insertion_point(class_scope:category.CategoryObj)
    private static final GRPCService.CategoryOuterClass.CategoryObj DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new GRPCService.CategoryOuterClass.CategoryObj();
    }

    public static GRPCService.CategoryOuterClass.CategoryObj getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CategoryObj>
        PARSER = new com.google.protobuf.AbstractParser<CategoryObj>() {
      @java.lang.Override
      public CategoryObj parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CategoryObj(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CategoryObj> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CategoryObj> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public GRPCService.CategoryOuterClass.CategoryObj getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ListOfCategoryObjOrBuilder extends
      // @@protoc_insertion_point(interface_extends:category.ListOfCategoryObj)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .category.CategoryObj allCategories = 1;</code>
     */
    java.util.List<GRPCService.CategoryOuterClass.CategoryObj> 
        getAllCategoriesList();
    /**
     * <code>repeated .category.CategoryObj allCategories = 1;</code>
     */
    GRPCService.CategoryOuterClass.CategoryObj getAllCategories(int index);
    /**
     * <code>repeated .category.CategoryObj allCategories = 1;</code>
     */
    int getAllCategoriesCount();
    /**
     * <code>repeated .category.CategoryObj allCategories = 1;</code>
     */
    java.util.List<? extends GRPCService.CategoryOuterClass.CategoryObjOrBuilder> 
        getAllCategoriesOrBuilderList();
    /**
     * <code>repeated .category.CategoryObj allCategories = 1;</code>
     */
    GRPCService.CategoryOuterClass.CategoryObjOrBuilder getAllCategoriesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code category.ListOfCategoryObj}
   */
  public  static final class ListOfCategoryObj extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:category.ListOfCategoryObj)
      ListOfCategoryObjOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ListOfCategoryObj.newBuilder() to construct.
    private ListOfCategoryObj(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ListOfCategoryObj() {
      allCategories_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ListOfCategoryObj(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                allCategories_ = new java.util.ArrayList<GRPCService.CategoryOuterClass.CategoryObj>();
                mutable_bitField0_ |= 0x00000001;
              }
              allCategories_.add(
                  input.readMessage(GRPCService.CategoryOuterClass.CategoryObj.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          allCategories_ = java.util.Collections.unmodifiableList(allCategories_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return GRPCService.CategoryOuterClass.internal_static_category_ListOfCategoryObj_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return GRPCService.CategoryOuterClass.internal_static_category_ListOfCategoryObj_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              GRPCService.CategoryOuterClass.ListOfCategoryObj.class, GRPCService.CategoryOuterClass.ListOfCategoryObj.Builder.class);
    }

    public static final int ALLCATEGORIES_FIELD_NUMBER = 1;
    private java.util.List<GRPCService.CategoryOuterClass.CategoryObj> allCategories_;
    /**
     * <code>repeated .category.CategoryObj allCategories = 1;</code>
     */
    public java.util.List<GRPCService.CategoryOuterClass.CategoryObj> getAllCategoriesList() {
      return allCategories_;
    }
    /**
     * <code>repeated .category.CategoryObj allCategories = 1;</code>
     */
    public java.util.List<? extends GRPCService.CategoryOuterClass.CategoryObjOrBuilder> 
        getAllCategoriesOrBuilderList() {
      return allCategories_;
    }
    /**
     * <code>repeated .category.CategoryObj allCategories = 1;</code>
     */
    public int getAllCategoriesCount() {
      return allCategories_.size();
    }
    /**
     * <code>repeated .category.CategoryObj allCategories = 1;</code>
     */
    public GRPCService.CategoryOuterClass.CategoryObj getAllCategories(int index) {
      return allCategories_.get(index);
    }
    /**
     * <code>repeated .category.CategoryObj allCategories = 1;</code>
     */
    public GRPCService.CategoryOuterClass.CategoryObjOrBuilder getAllCategoriesOrBuilder(
        int index) {
      return allCategories_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < allCategories_.size(); i++) {
        output.writeMessage(1, allCategories_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < allCategories_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, allCategories_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof GRPCService.CategoryOuterClass.ListOfCategoryObj)) {
        return super.equals(obj);
      }
      GRPCService.CategoryOuterClass.ListOfCategoryObj other = (GRPCService.CategoryOuterClass.ListOfCategoryObj) obj;

      boolean result = true;
      result = result && getAllCategoriesList()
          .equals(other.getAllCategoriesList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getAllCategoriesCount() > 0) {
        hash = (37 * hash) + ALLCATEGORIES_FIELD_NUMBER;
        hash = (53 * hash) + getAllCategoriesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static GRPCService.CategoryOuterClass.ListOfCategoryObj parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GRPCService.CategoryOuterClass.ListOfCategoryObj parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GRPCService.CategoryOuterClass.ListOfCategoryObj parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GRPCService.CategoryOuterClass.ListOfCategoryObj parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GRPCService.CategoryOuterClass.ListOfCategoryObj parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GRPCService.CategoryOuterClass.ListOfCategoryObj parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GRPCService.CategoryOuterClass.ListOfCategoryObj parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GRPCService.CategoryOuterClass.ListOfCategoryObj parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static GRPCService.CategoryOuterClass.ListOfCategoryObj parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static GRPCService.CategoryOuterClass.ListOfCategoryObj parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static GRPCService.CategoryOuterClass.ListOfCategoryObj parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GRPCService.CategoryOuterClass.ListOfCategoryObj parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(GRPCService.CategoryOuterClass.ListOfCategoryObj prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code category.ListOfCategoryObj}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:category.ListOfCategoryObj)
        GRPCService.CategoryOuterClass.ListOfCategoryObjOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return GRPCService.CategoryOuterClass.internal_static_category_ListOfCategoryObj_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return GRPCService.CategoryOuterClass.internal_static_category_ListOfCategoryObj_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                GRPCService.CategoryOuterClass.ListOfCategoryObj.class, GRPCService.CategoryOuterClass.ListOfCategoryObj.Builder.class);
      }

      // Construct using GRPCService.CategoryOuterClass.ListOfCategoryObj.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getAllCategoriesFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (allCategoriesBuilder_ == null) {
          allCategories_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          allCategoriesBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return GRPCService.CategoryOuterClass.internal_static_category_ListOfCategoryObj_descriptor;
      }

      @java.lang.Override
      public GRPCService.CategoryOuterClass.ListOfCategoryObj getDefaultInstanceForType() {
        return GRPCService.CategoryOuterClass.ListOfCategoryObj.getDefaultInstance();
      }

      @java.lang.Override
      public GRPCService.CategoryOuterClass.ListOfCategoryObj build() {
        GRPCService.CategoryOuterClass.ListOfCategoryObj result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public GRPCService.CategoryOuterClass.ListOfCategoryObj buildPartial() {
        GRPCService.CategoryOuterClass.ListOfCategoryObj result = new GRPCService.CategoryOuterClass.ListOfCategoryObj(this);
        int from_bitField0_ = bitField0_;
        if (allCategoriesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            allCategories_ = java.util.Collections.unmodifiableList(allCategories_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.allCategories_ = allCategories_;
        } else {
          result.allCategories_ = allCategoriesBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof GRPCService.CategoryOuterClass.ListOfCategoryObj) {
          return mergeFrom((GRPCService.CategoryOuterClass.ListOfCategoryObj)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(GRPCService.CategoryOuterClass.ListOfCategoryObj other) {
        if (other == GRPCService.CategoryOuterClass.ListOfCategoryObj.getDefaultInstance()) return this;
        if (allCategoriesBuilder_ == null) {
          if (!other.allCategories_.isEmpty()) {
            if (allCategories_.isEmpty()) {
              allCategories_ = other.allCategories_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureAllCategoriesIsMutable();
              allCategories_.addAll(other.allCategories_);
            }
            onChanged();
          }
        } else {
          if (!other.allCategories_.isEmpty()) {
            if (allCategoriesBuilder_.isEmpty()) {
              allCategoriesBuilder_.dispose();
              allCategoriesBuilder_ = null;
              allCategories_ = other.allCategories_;
              bitField0_ = (bitField0_ & ~0x00000001);
              allCategoriesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getAllCategoriesFieldBuilder() : null;
            } else {
              allCategoriesBuilder_.addAllMessages(other.allCategories_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        GRPCService.CategoryOuterClass.ListOfCategoryObj parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (GRPCService.CategoryOuterClass.ListOfCategoryObj) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<GRPCService.CategoryOuterClass.CategoryObj> allCategories_ =
        java.util.Collections.emptyList();
      private void ensureAllCategoriesIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          allCategories_ = new java.util.ArrayList<GRPCService.CategoryOuterClass.CategoryObj>(allCategories_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          GRPCService.CategoryOuterClass.CategoryObj, GRPCService.CategoryOuterClass.CategoryObj.Builder, GRPCService.CategoryOuterClass.CategoryObjOrBuilder> allCategoriesBuilder_;

      /**
       * <code>repeated .category.CategoryObj allCategories = 1;</code>
       */
      public java.util.List<GRPCService.CategoryOuterClass.CategoryObj> getAllCategoriesList() {
        if (allCategoriesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(allCategories_);
        } else {
          return allCategoriesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .category.CategoryObj allCategories = 1;</code>
       */
      public int getAllCategoriesCount() {
        if (allCategoriesBuilder_ == null) {
          return allCategories_.size();
        } else {
          return allCategoriesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .category.CategoryObj allCategories = 1;</code>
       */
      public GRPCService.CategoryOuterClass.CategoryObj getAllCategories(int index) {
        if (allCategoriesBuilder_ == null) {
          return allCategories_.get(index);
        } else {
          return allCategoriesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .category.CategoryObj allCategories = 1;</code>
       */
      public Builder setAllCategories(
          int index, GRPCService.CategoryOuterClass.CategoryObj value) {
        if (allCategoriesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAllCategoriesIsMutable();
          allCategories_.set(index, value);
          onChanged();
        } else {
          allCategoriesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .category.CategoryObj allCategories = 1;</code>
       */
      public Builder setAllCategories(
          int index, GRPCService.CategoryOuterClass.CategoryObj.Builder builderForValue) {
        if (allCategoriesBuilder_ == null) {
          ensureAllCategoriesIsMutable();
          allCategories_.set(index, builderForValue.build());
          onChanged();
        } else {
          allCategoriesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .category.CategoryObj allCategories = 1;</code>
       */
      public Builder addAllCategories(GRPCService.CategoryOuterClass.CategoryObj value) {
        if (allCategoriesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAllCategoriesIsMutable();
          allCategories_.add(value);
          onChanged();
        } else {
          allCategoriesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .category.CategoryObj allCategories = 1;</code>
       */
      public Builder addAllCategories(
          int index, GRPCService.CategoryOuterClass.CategoryObj value) {
        if (allCategoriesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAllCategoriesIsMutable();
          allCategories_.add(index, value);
          onChanged();
        } else {
          allCategoriesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .category.CategoryObj allCategories = 1;</code>
       */
      public Builder addAllCategories(
          GRPCService.CategoryOuterClass.CategoryObj.Builder builderForValue) {
        if (allCategoriesBuilder_ == null) {
          ensureAllCategoriesIsMutable();
          allCategories_.add(builderForValue.build());
          onChanged();
        } else {
          allCategoriesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .category.CategoryObj allCategories = 1;</code>
       */
      public Builder addAllCategories(
          int index, GRPCService.CategoryOuterClass.CategoryObj.Builder builderForValue) {
        if (allCategoriesBuilder_ == null) {
          ensureAllCategoriesIsMutable();
          allCategories_.add(index, builderForValue.build());
          onChanged();
        } else {
          allCategoriesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .category.CategoryObj allCategories = 1;</code>
       */
      public Builder addAllAllCategories(
          java.lang.Iterable<? extends GRPCService.CategoryOuterClass.CategoryObj> values) {
        if (allCategoriesBuilder_ == null) {
          ensureAllCategoriesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, allCategories_);
          onChanged();
        } else {
          allCategoriesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .category.CategoryObj allCategories = 1;</code>
       */
      public Builder clearAllCategories() {
        if (allCategoriesBuilder_ == null) {
          allCategories_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          allCategoriesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .category.CategoryObj allCategories = 1;</code>
       */
      public Builder removeAllCategories(int index) {
        if (allCategoriesBuilder_ == null) {
          ensureAllCategoriesIsMutable();
          allCategories_.remove(index);
          onChanged();
        } else {
          allCategoriesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .category.CategoryObj allCategories = 1;</code>
       */
      public GRPCService.CategoryOuterClass.CategoryObj.Builder getAllCategoriesBuilder(
          int index) {
        return getAllCategoriesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .category.CategoryObj allCategories = 1;</code>
       */
      public GRPCService.CategoryOuterClass.CategoryObjOrBuilder getAllCategoriesOrBuilder(
          int index) {
        if (allCategoriesBuilder_ == null) {
          return allCategories_.get(index);  } else {
          return allCategoriesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .category.CategoryObj allCategories = 1;</code>
       */
      public java.util.List<? extends GRPCService.CategoryOuterClass.CategoryObjOrBuilder> 
           getAllCategoriesOrBuilderList() {
        if (allCategoriesBuilder_ != null) {
          return allCategoriesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(allCategories_);
        }
      }
      /**
       * <code>repeated .category.CategoryObj allCategories = 1;</code>
       */
      public GRPCService.CategoryOuterClass.CategoryObj.Builder addAllCategoriesBuilder() {
        return getAllCategoriesFieldBuilder().addBuilder(
            GRPCService.CategoryOuterClass.CategoryObj.getDefaultInstance());
      }
      /**
       * <code>repeated .category.CategoryObj allCategories = 1;</code>
       */
      public GRPCService.CategoryOuterClass.CategoryObj.Builder addAllCategoriesBuilder(
          int index) {
        return getAllCategoriesFieldBuilder().addBuilder(
            index, GRPCService.CategoryOuterClass.CategoryObj.getDefaultInstance());
      }
      /**
       * <code>repeated .category.CategoryObj allCategories = 1;</code>
       */
      public java.util.List<GRPCService.CategoryOuterClass.CategoryObj.Builder> 
           getAllCategoriesBuilderList() {
        return getAllCategoriesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          GRPCService.CategoryOuterClass.CategoryObj, GRPCService.CategoryOuterClass.CategoryObj.Builder, GRPCService.CategoryOuterClass.CategoryObjOrBuilder> 
          getAllCategoriesFieldBuilder() {
        if (allCategoriesBuilder_ == null) {
          allCategoriesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              GRPCService.CategoryOuterClass.CategoryObj, GRPCService.CategoryOuterClass.CategoryObj.Builder, GRPCService.CategoryOuterClass.CategoryObjOrBuilder>(
                  allCategories_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          allCategories_ = null;
        }
        return allCategoriesBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:category.ListOfCategoryObj)
    }

    // @@protoc_insertion_point(class_scope:category.ListOfCategoryObj)
    private static final GRPCService.CategoryOuterClass.ListOfCategoryObj DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new GRPCService.CategoryOuterClass.ListOfCategoryObj();
    }

    public static GRPCService.CategoryOuterClass.ListOfCategoryObj getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ListOfCategoryObj>
        PARSER = new com.google.protobuf.AbstractParser<ListOfCategoryObj>() {
      @java.lang.Override
      public ListOfCategoryObj parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ListOfCategoryObj(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ListOfCategoryObj> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ListOfCategoryObj> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public GRPCService.CategoryOuterClass.ListOfCategoryObj getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface EmptyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:category.Empty)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code category.Empty}
   */
  public  static final class Empty extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:category.Empty)
      EmptyOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Empty.newBuilder() to construct.
    private Empty(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Empty() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Empty(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return GRPCService.CategoryOuterClass.internal_static_category_Empty_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return GRPCService.CategoryOuterClass.internal_static_category_Empty_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              GRPCService.CategoryOuterClass.Empty.class, GRPCService.CategoryOuterClass.Empty.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof GRPCService.CategoryOuterClass.Empty)) {
        return super.equals(obj);
      }
      GRPCService.CategoryOuterClass.Empty other = (GRPCService.CategoryOuterClass.Empty) obj;

      boolean result = true;
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static GRPCService.CategoryOuterClass.Empty parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GRPCService.CategoryOuterClass.Empty parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GRPCService.CategoryOuterClass.Empty parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GRPCService.CategoryOuterClass.Empty parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GRPCService.CategoryOuterClass.Empty parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GRPCService.CategoryOuterClass.Empty parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GRPCService.CategoryOuterClass.Empty parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GRPCService.CategoryOuterClass.Empty parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static GRPCService.CategoryOuterClass.Empty parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static GRPCService.CategoryOuterClass.Empty parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static GRPCService.CategoryOuterClass.Empty parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GRPCService.CategoryOuterClass.Empty parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(GRPCService.CategoryOuterClass.Empty prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code category.Empty}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:category.Empty)
        GRPCService.CategoryOuterClass.EmptyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return GRPCService.CategoryOuterClass.internal_static_category_Empty_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return GRPCService.CategoryOuterClass.internal_static_category_Empty_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                GRPCService.CategoryOuterClass.Empty.class, GRPCService.CategoryOuterClass.Empty.Builder.class);
      }

      // Construct using GRPCService.CategoryOuterClass.Empty.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return GRPCService.CategoryOuterClass.internal_static_category_Empty_descriptor;
      }

      @java.lang.Override
      public GRPCService.CategoryOuterClass.Empty getDefaultInstanceForType() {
        return GRPCService.CategoryOuterClass.Empty.getDefaultInstance();
      }

      @java.lang.Override
      public GRPCService.CategoryOuterClass.Empty build() {
        GRPCService.CategoryOuterClass.Empty result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public GRPCService.CategoryOuterClass.Empty buildPartial() {
        GRPCService.CategoryOuterClass.Empty result = new GRPCService.CategoryOuterClass.Empty(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof GRPCService.CategoryOuterClass.Empty) {
          return mergeFrom((GRPCService.CategoryOuterClass.Empty)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(GRPCService.CategoryOuterClass.Empty other) {
        if (other == GRPCService.CategoryOuterClass.Empty.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        GRPCService.CategoryOuterClass.Empty parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (GRPCService.CategoryOuterClass.Empty) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:category.Empty)
    }

    // @@protoc_insertion_point(class_scope:category.Empty)
    private static final GRPCService.CategoryOuterClass.Empty DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new GRPCService.CategoryOuterClass.Empty();
    }

    public static GRPCService.CategoryOuterClass.Empty getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Empty>
        PARSER = new com.google.protobuf.AbstractParser<Empty>() {
      @java.lang.Override
      public Empty parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Empty(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Empty> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Empty> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public GRPCService.CategoryOuterClass.Empty getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_category_CategoryObj_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_category_CategoryObj_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_category_ListOfCategoryObj_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_category_ListOfCategoryObj_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_category_Empty_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_category_Empty_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016category.proto\022\010category\032\nuser.proto\032\021" +
      "subcategory.proto\"[\n\013CategoryObj\022\n\n\002id\030\001" +
      " \001(\005\022\014\n\004name\030\002 \001(\t\0222\n\rsubCategories\030\003 \003(" +
      "\0132\033.subcategory.SubcategoryObj\"A\n\021ListOf" +
      "CategoryObj\022,\n\rallCategories\030\001 \003(\0132\025.cat" +
      "egory.CategoryObj\"\007\n\005Empty2L\n\010Category\022@" +
      "\n\020GetAllCategories\022\017.category.Empty\032\033.ca" +
      "tegory.ListOfCategoryObjB\r\n\013GRPCServiceb" +
      "\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          GRPCService.UserOuterClass.getDescriptor(),
          GRPCService.Subcategory.getDescriptor(),
        }, assigner);
    internal_static_category_CategoryObj_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_category_CategoryObj_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_category_CategoryObj_descriptor,
        new java.lang.String[] { "Id", "Name", "SubCategories", });
    internal_static_category_ListOfCategoryObj_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_category_ListOfCategoryObj_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_category_ListOfCategoryObj_descriptor,
        new java.lang.String[] { "AllCategories", });
    internal_static_category_Empty_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_category_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_category_Empty_descriptor,
        new java.lang.String[] { });
    GRPCService.UserOuterClass.getDescriptor();
    GRPCService.Subcategory.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
