// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: comment.proto

package GRPCService;

public final class Comment {
  private Comment() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CommentObjOrBuilder extends
      // @@protoc_insertion_point(interface_extends:comment.CommentObj)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>string body = 2;</code>
     */
    java.lang.String getBody();
    /**
     * <code>string body = 2;</code>
     */
    com.google.protobuf.ByteString
        getBodyBytes();

    /**
     * <code>.user.UserObj writer = 3;</code>
     */
    boolean hasWriter();
    /**
     * <code>.user.UserObj writer = 3;</code>
     */
    GRPCService.UserOuterClass.UserObj getWriter();
    /**
     * <code>.user.UserObj writer = 3;</code>
     */
    GRPCService.UserOuterClass.UserObjOrBuilder getWriterOrBuilder();
  }
  /**
   * Protobuf type {@code comment.CommentObj}
   */
  public  static final class CommentObj extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:comment.CommentObj)
      CommentObjOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CommentObj.newBuilder() to construct.
    private CommentObj(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CommentObj() {
      id_ = 0;
      body_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CommentObj(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              body_ = s;
              break;
            }
            case 26: {
              GRPCService.UserOuterClass.UserObj.Builder subBuilder = null;
              if (writer_ != null) {
                subBuilder = writer_.toBuilder();
              }
              writer_ = input.readMessage(GRPCService.UserOuterClass.UserObj.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(writer_);
                writer_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return GRPCService.Comment.internal_static_comment_CommentObj_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return GRPCService.Comment.internal_static_comment_CommentObj_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              GRPCService.Comment.CommentObj.class, GRPCService.Comment.CommentObj.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int BODY_FIELD_NUMBER = 2;
    private volatile java.lang.Object body_;
    /**
     * <code>string body = 2;</code>
     */
    public java.lang.String getBody() {
      java.lang.Object ref = body_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        body_ = s;
        return s;
      }
    }
    /**
     * <code>string body = 2;</code>
     */
    public com.google.protobuf.ByteString
        getBodyBytes() {
      java.lang.Object ref = body_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        body_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int WRITER_FIELD_NUMBER = 3;
    private GRPCService.UserOuterClass.UserObj writer_;
    /**
     * <code>.user.UserObj writer = 3;</code>
     */
    public boolean hasWriter() {
      return writer_ != null;
    }
    /**
     * <code>.user.UserObj writer = 3;</code>
     */
    public GRPCService.UserOuterClass.UserObj getWriter() {
      return writer_ == null ? GRPCService.UserOuterClass.UserObj.getDefaultInstance() : writer_;
    }
    /**
     * <code>.user.UserObj writer = 3;</code>
     */
    public GRPCService.UserOuterClass.UserObjOrBuilder getWriterOrBuilder() {
      return getWriter();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!getBodyBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, body_);
      }
      if (writer_ != null) {
        output.writeMessage(3, getWriter());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!getBodyBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, body_);
      }
      if (writer_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getWriter());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof GRPCService.Comment.CommentObj)) {
        return super.equals(obj);
      }
      GRPCService.Comment.CommentObj other = (GRPCService.Comment.CommentObj) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && getBody()
          .equals(other.getBody());
      result = result && (hasWriter() == other.hasWriter());
      if (hasWriter()) {
        result = result && getWriter()
            .equals(other.getWriter());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + BODY_FIELD_NUMBER;
      hash = (53 * hash) + getBody().hashCode();
      if (hasWriter()) {
        hash = (37 * hash) + WRITER_FIELD_NUMBER;
        hash = (53 * hash) + getWriter().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static GRPCService.Comment.CommentObj parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GRPCService.Comment.CommentObj parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GRPCService.Comment.CommentObj parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GRPCService.Comment.CommentObj parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GRPCService.Comment.CommentObj parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GRPCService.Comment.CommentObj parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GRPCService.Comment.CommentObj parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GRPCService.Comment.CommentObj parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static GRPCService.Comment.CommentObj parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static GRPCService.Comment.CommentObj parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static GRPCService.Comment.CommentObj parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GRPCService.Comment.CommentObj parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(GRPCService.Comment.CommentObj prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code comment.CommentObj}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:comment.CommentObj)
        GRPCService.Comment.CommentObjOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return GRPCService.Comment.internal_static_comment_CommentObj_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return GRPCService.Comment.internal_static_comment_CommentObj_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                GRPCService.Comment.CommentObj.class, GRPCService.Comment.CommentObj.Builder.class);
      }

      // Construct using GRPCService.Comment.CommentObj.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        body_ = "";

        if (writerBuilder_ == null) {
          writer_ = null;
        } else {
          writer_ = null;
          writerBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return GRPCService.Comment.internal_static_comment_CommentObj_descriptor;
      }

      @java.lang.Override
      public GRPCService.Comment.CommentObj getDefaultInstanceForType() {
        return GRPCService.Comment.CommentObj.getDefaultInstance();
      }

      @java.lang.Override
      public GRPCService.Comment.CommentObj build() {
        GRPCService.Comment.CommentObj result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public GRPCService.Comment.CommentObj buildPartial() {
        GRPCService.Comment.CommentObj result = new GRPCService.Comment.CommentObj(this);
        result.id_ = id_;
        result.body_ = body_;
        if (writerBuilder_ == null) {
          result.writer_ = writer_;
        } else {
          result.writer_ = writerBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof GRPCService.Comment.CommentObj) {
          return mergeFrom((GRPCService.Comment.CommentObj)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(GRPCService.Comment.CommentObj other) {
        if (other == GRPCService.Comment.CommentObj.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getBody().isEmpty()) {
          body_ = other.body_;
          onChanged();
        }
        if (other.hasWriter()) {
          mergeWriter(other.getWriter());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        GRPCService.Comment.CommentObj parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (GRPCService.Comment.CommentObj) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object body_ = "";
      /**
       * <code>string body = 2;</code>
       */
      public java.lang.String getBody() {
        java.lang.Object ref = body_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          body_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string body = 2;</code>
       */
      public com.google.protobuf.ByteString
          getBodyBytes() {
        java.lang.Object ref = body_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          body_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string body = 2;</code>
       */
      public Builder setBody(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        body_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string body = 2;</code>
       */
      public Builder clearBody() {
        
        body_ = getDefaultInstance().getBody();
        onChanged();
        return this;
      }
      /**
       * <code>string body = 2;</code>
       */
      public Builder setBodyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        body_ = value;
        onChanged();
        return this;
      }

      private GRPCService.UserOuterClass.UserObj writer_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          GRPCService.UserOuterClass.UserObj, GRPCService.UserOuterClass.UserObj.Builder, GRPCService.UserOuterClass.UserObjOrBuilder> writerBuilder_;
      /**
       * <code>.user.UserObj writer = 3;</code>
       */
      public boolean hasWriter() {
        return writerBuilder_ != null || writer_ != null;
      }
      /**
       * <code>.user.UserObj writer = 3;</code>
       */
      public GRPCService.UserOuterClass.UserObj getWriter() {
        if (writerBuilder_ == null) {
          return writer_ == null ? GRPCService.UserOuterClass.UserObj.getDefaultInstance() : writer_;
        } else {
          return writerBuilder_.getMessage();
        }
      }
      /**
       * <code>.user.UserObj writer = 3;</code>
       */
      public Builder setWriter(GRPCService.UserOuterClass.UserObj value) {
        if (writerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          writer_ = value;
          onChanged();
        } else {
          writerBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.user.UserObj writer = 3;</code>
       */
      public Builder setWriter(
          GRPCService.UserOuterClass.UserObj.Builder builderForValue) {
        if (writerBuilder_ == null) {
          writer_ = builderForValue.build();
          onChanged();
        } else {
          writerBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.user.UserObj writer = 3;</code>
       */
      public Builder mergeWriter(GRPCService.UserOuterClass.UserObj value) {
        if (writerBuilder_ == null) {
          if (writer_ != null) {
            writer_ =
              GRPCService.UserOuterClass.UserObj.newBuilder(writer_).mergeFrom(value).buildPartial();
          } else {
            writer_ = value;
          }
          onChanged();
        } else {
          writerBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.user.UserObj writer = 3;</code>
       */
      public Builder clearWriter() {
        if (writerBuilder_ == null) {
          writer_ = null;
          onChanged();
        } else {
          writer_ = null;
          writerBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.user.UserObj writer = 3;</code>
       */
      public GRPCService.UserOuterClass.UserObj.Builder getWriterBuilder() {
        
        onChanged();
        return getWriterFieldBuilder().getBuilder();
      }
      /**
       * <code>.user.UserObj writer = 3;</code>
       */
      public GRPCService.UserOuterClass.UserObjOrBuilder getWriterOrBuilder() {
        if (writerBuilder_ != null) {
          return writerBuilder_.getMessageOrBuilder();
        } else {
          return writer_ == null ?
              GRPCService.UserOuterClass.UserObj.getDefaultInstance() : writer_;
        }
      }
      /**
       * <code>.user.UserObj writer = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          GRPCService.UserOuterClass.UserObj, GRPCService.UserOuterClass.UserObj.Builder, GRPCService.UserOuterClass.UserObjOrBuilder> 
          getWriterFieldBuilder() {
        if (writerBuilder_ == null) {
          writerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              GRPCService.UserOuterClass.UserObj, GRPCService.UserOuterClass.UserObj.Builder, GRPCService.UserOuterClass.UserObjOrBuilder>(
                  getWriter(),
                  getParentForChildren(),
                  isClean());
          writer_ = null;
        }
        return writerBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:comment.CommentObj)
    }

    // @@protoc_insertion_point(class_scope:comment.CommentObj)
    private static final GRPCService.Comment.CommentObj DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new GRPCService.Comment.CommentObj();
    }

    public static GRPCService.Comment.CommentObj getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CommentObj>
        PARSER = new com.google.protobuf.AbstractParser<CommentObj>() {
      @java.lang.Override
      public CommentObj parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CommentObj(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CommentObj> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CommentObj> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public GRPCService.Comment.CommentObj getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_comment_CommentObj_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_comment_CommentObj_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rcomment.proto\022\007comment\032\nuser.proto\"E\n\n" +
      "CommentObj\022\n\n\002id\030\001 \001(\005\022\014\n\004body\030\002 \001(\t\022\035\n\006" +
      "writer\030\003 \001(\0132\r.user.UserObj2\t\n\007commentB\r" +
      "\n\013GRPCServiceb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          GRPCService.UserOuterClass.getDescriptor(),
        }, assigner);
    internal_static_comment_CommentObj_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_comment_CommentObj_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_comment_CommentObj_descriptor,
        new java.lang.String[] { "Id", "Body", "Writer", });
    GRPCService.UserOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
