// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: post.proto

package GRPCService;

public final class PostOuterClass {
  private PostOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PostObjOrBuilder extends
      // @@protoc_insertion_point(interface_extends:post.PostObj)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>string title = 2;</code>
     */
    java.lang.String getTitle();
    /**
     * <code>string title = 2;</code>
     */
    com.google.protobuf.ByteString
        getTitleBytes();

    /**
     * <code>string description = 3;</code>
     */
    java.lang.String getDescription();
    /**
     * <code>string description = 3;</code>
     */
    com.google.protobuf.ByteString
        getDescriptionBytes();

    /**
     * <code>int32 price = 4;</code>
     */
    int getPrice();

    /**
     * <code>string address = 5;</code>
     */
    java.lang.String getAddress();
    /**
     * <code>string address = 5;</code>
     */
    com.google.protobuf.ByteString
        getAddressBytes();

    /**
     * <code>string condition = 6;</code>
     */
    java.lang.String getCondition();
    /**
     * <code>string condition = 6;</code>
     */
    com.google.protobuf.ByteString
        getConditionBytes();

    /**
     * <code>string phoneNumber = 7;</code>
     */
    java.lang.String getPhoneNumber();
    /**
     * <code>string phoneNumber = 7;</code>
     */
    com.google.protobuf.ByteString
        getPhoneNumberBytes();

    /**
     * <code>string email = 8;</code>
     */
    java.lang.String getEmail();
    /**
     * <code>string email = 8;</code>
     */
    com.google.protobuf.ByteString
        getEmailBytes();

    /**
     * <code>.user.UserObj writer = 9;</code>
     */
    boolean hasWriter();
    /**
     * <code>.user.UserObj writer = 9;</code>
     */
    GRPCService.UserOuterClass.UserObj getWriter();
    /**
     * <code>.user.UserObj writer = 9;</code>
     */
    GRPCService.UserOuterClass.UserObjOrBuilder getWriterOrBuilder();

    /**
     * <code>repeated .image.ImageObj images = 10;</code>
     */
    java.util.List<GRPCService.Image.ImageObj> 
        getImagesList();
    /**
     * <code>repeated .image.ImageObj images = 10;</code>
     */
    GRPCService.Image.ImageObj getImages(int index);
    /**
     * <code>repeated .image.ImageObj images = 10;</code>
     */
    int getImagesCount();
    /**
     * <code>repeated .image.ImageObj images = 10;</code>
     */
    java.util.List<? extends GRPCService.Image.ImageObjOrBuilder> 
        getImagesOrBuilderList();
    /**
     * <code>repeated .image.ImageObj images = 10;</code>
     */
    GRPCService.Image.ImageObjOrBuilder getImagesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code post.PostObj}
   */
  public  static final class PostObj extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:post.PostObj)
      PostObjOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PostObj.newBuilder() to construct.
    private PostObj(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PostObj() {
      id_ = 0;
      title_ = "";
      description_ = "";
      price_ = 0;
      address_ = "";
      condition_ = "";
      phoneNumber_ = "";
      email_ = "";
      images_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PostObj(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              title_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              description_ = s;
              break;
            }
            case 32: {

              price_ = input.readInt32();
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              address_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              condition_ = s;
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              phoneNumber_ = s;
              break;
            }
            case 66: {
              java.lang.String s = input.readStringRequireUtf8();

              email_ = s;
              break;
            }
            case 74: {
              GRPCService.UserOuterClass.UserObj.Builder subBuilder = null;
              if (writer_ != null) {
                subBuilder = writer_.toBuilder();
              }
              writer_ = input.readMessage(GRPCService.UserOuterClass.UserObj.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(writer_);
                writer_ = subBuilder.buildPartial();
              }

              break;
            }
            case 82: {
              if (!((mutable_bitField0_ & 0x00000200) == 0x00000200)) {
                images_ = new java.util.ArrayList<GRPCService.Image.ImageObj>();
                mutable_bitField0_ |= 0x00000200;
              }
              images_.add(
                  input.readMessage(GRPCService.Image.ImageObj.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000200) == 0x00000200)) {
          images_ = java.util.Collections.unmodifiableList(images_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return GRPCService.PostOuterClass.internal_static_post_PostObj_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return GRPCService.PostOuterClass.internal_static_post_PostObj_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              GRPCService.PostOuterClass.PostObj.class, GRPCService.PostOuterClass.PostObj.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int TITLE_FIELD_NUMBER = 2;
    private volatile java.lang.Object title_;
    /**
     * <code>string title = 2;</code>
     */
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        title_ = s;
        return s;
      }
    }
    /**
     * <code>string title = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DESCRIPTION_FIELD_NUMBER = 3;
    private volatile java.lang.Object description_;
    /**
     * <code>string description = 3;</code>
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      }
    }
    /**
     * <code>string description = 3;</code>
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PRICE_FIELD_NUMBER = 4;
    private int price_;
    /**
     * <code>int32 price = 4;</code>
     */
    public int getPrice() {
      return price_;
    }

    public static final int ADDRESS_FIELD_NUMBER = 5;
    private volatile java.lang.Object address_;
    /**
     * <code>string address = 5;</code>
     */
    public java.lang.String getAddress() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        address_ = s;
        return s;
      }
    }
    /**
     * <code>string address = 5;</code>
     */
    public com.google.protobuf.ByteString
        getAddressBytes() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        address_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONDITION_FIELD_NUMBER = 6;
    private volatile java.lang.Object condition_;
    /**
     * <code>string condition = 6;</code>
     */
    public java.lang.String getCondition() {
      java.lang.Object ref = condition_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        condition_ = s;
        return s;
      }
    }
    /**
     * <code>string condition = 6;</code>
     */
    public com.google.protobuf.ByteString
        getConditionBytes() {
      java.lang.Object ref = condition_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        condition_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PHONENUMBER_FIELD_NUMBER = 7;
    private volatile java.lang.Object phoneNumber_;
    /**
     * <code>string phoneNumber = 7;</code>
     */
    public java.lang.String getPhoneNumber() {
      java.lang.Object ref = phoneNumber_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        phoneNumber_ = s;
        return s;
      }
    }
    /**
     * <code>string phoneNumber = 7;</code>
     */
    public com.google.protobuf.ByteString
        getPhoneNumberBytes() {
      java.lang.Object ref = phoneNumber_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        phoneNumber_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EMAIL_FIELD_NUMBER = 8;
    private volatile java.lang.Object email_;
    /**
     * <code>string email = 8;</code>
     */
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        email_ = s;
        return s;
      }
    }
    /**
     * <code>string email = 8;</code>
     */
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int WRITER_FIELD_NUMBER = 9;
    private GRPCService.UserOuterClass.UserObj writer_;
    /**
     * <code>.user.UserObj writer = 9;</code>
     */
    public boolean hasWriter() {
      return writer_ != null;
    }
    /**
     * <code>.user.UserObj writer = 9;</code>
     */
    public GRPCService.UserOuterClass.UserObj getWriter() {
      return writer_ == null ? GRPCService.UserOuterClass.UserObj.getDefaultInstance() : writer_;
    }
    /**
     * <code>.user.UserObj writer = 9;</code>
     */
    public GRPCService.UserOuterClass.UserObjOrBuilder getWriterOrBuilder() {
      return getWriter();
    }

    public static final int IMAGES_FIELD_NUMBER = 10;
    private java.util.List<GRPCService.Image.ImageObj> images_;
    /**
     * <code>repeated .image.ImageObj images = 10;</code>
     */
    public java.util.List<GRPCService.Image.ImageObj> getImagesList() {
      return images_;
    }
    /**
     * <code>repeated .image.ImageObj images = 10;</code>
     */
    public java.util.List<? extends GRPCService.Image.ImageObjOrBuilder> 
        getImagesOrBuilderList() {
      return images_;
    }
    /**
     * <code>repeated .image.ImageObj images = 10;</code>
     */
    public int getImagesCount() {
      return images_.size();
    }
    /**
     * <code>repeated .image.ImageObj images = 10;</code>
     */
    public GRPCService.Image.ImageObj getImages(int index) {
      return images_.get(index);
    }
    /**
     * <code>repeated .image.ImageObj images = 10;</code>
     */
    public GRPCService.Image.ImageObjOrBuilder getImagesOrBuilder(
        int index) {
      return images_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!getTitleBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, title_);
      }
      if (!getDescriptionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, description_);
      }
      if (price_ != 0) {
        output.writeInt32(4, price_);
      }
      if (!getAddressBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, address_);
      }
      if (!getConditionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, condition_);
      }
      if (!getPhoneNumberBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, phoneNumber_);
      }
      if (!getEmailBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, email_);
      }
      if (writer_ != null) {
        output.writeMessage(9, getWriter());
      }
      for (int i = 0; i < images_.size(); i++) {
        output.writeMessage(10, images_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!getTitleBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, title_);
      }
      if (!getDescriptionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, description_);
      }
      if (price_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, price_);
      }
      if (!getAddressBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, address_);
      }
      if (!getConditionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, condition_);
      }
      if (!getPhoneNumberBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, phoneNumber_);
      }
      if (!getEmailBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, email_);
      }
      if (writer_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(9, getWriter());
      }
      for (int i = 0; i < images_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(10, images_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof GRPCService.PostOuterClass.PostObj)) {
        return super.equals(obj);
      }
      GRPCService.PostOuterClass.PostObj other = (GRPCService.PostOuterClass.PostObj) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && getTitle()
          .equals(other.getTitle());
      result = result && getDescription()
          .equals(other.getDescription());
      result = result && (getPrice()
          == other.getPrice());
      result = result && getAddress()
          .equals(other.getAddress());
      result = result && getCondition()
          .equals(other.getCondition());
      result = result && getPhoneNumber()
          .equals(other.getPhoneNumber());
      result = result && getEmail()
          .equals(other.getEmail());
      result = result && (hasWriter() == other.hasWriter());
      if (hasWriter()) {
        result = result && getWriter()
            .equals(other.getWriter());
      }
      result = result && getImagesList()
          .equals(other.getImagesList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + TITLE_FIELD_NUMBER;
      hash = (53 * hash) + getTitle().hashCode();
      hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
      hash = (53 * hash) + getDescription().hashCode();
      hash = (37 * hash) + PRICE_FIELD_NUMBER;
      hash = (53 * hash) + getPrice();
      hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getAddress().hashCode();
      hash = (37 * hash) + CONDITION_FIELD_NUMBER;
      hash = (53 * hash) + getCondition().hashCode();
      hash = (37 * hash) + PHONENUMBER_FIELD_NUMBER;
      hash = (53 * hash) + getPhoneNumber().hashCode();
      hash = (37 * hash) + EMAIL_FIELD_NUMBER;
      hash = (53 * hash) + getEmail().hashCode();
      if (hasWriter()) {
        hash = (37 * hash) + WRITER_FIELD_NUMBER;
        hash = (53 * hash) + getWriter().hashCode();
      }
      if (getImagesCount() > 0) {
        hash = (37 * hash) + IMAGES_FIELD_NUMBER;
        hash = (53 * hash) + getImagesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static GRPCService.PostOuterClass.PostObj parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GRPCService.PostOuterClass.PostObj parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GRPCService.PostOuterClass.PostObj parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GRPCService.PostOuterClass.PostObj parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GRPCService.PostOuterClass.PostObj parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GRPCService.PostOuterClass.PostObj parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GRPCService.PostOuterClass.PostObj parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GRPCService.PostOuterClass.PostObj parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static GRPCService.PostOuterClass.PostObj parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static GRPCService.PostOuterClass.PostObj parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static GRPCService.PostOuterClass.PostObj parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GRPCService.PostOuterClass.PostObj parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(GRPCService.PostOuterClass.PostObj prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code post.PostObj}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:post.PostObj)
        GRPCService.PostOuterClass.PostObjOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return GRPCService.PostOuterClass.internal_static_post_PostObj_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return GRPCService.PostOuterClass.internal_static_post_PostObj_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                GRPCService.PostOuterClass.PostObj.class, GRPCService.PostOuterClass.PostObj.Builder.class);
      }

      // Construct using GRPCService.PostOuterClass.PostObj.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getImagesFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        title_ = "";

        description_ = "";

        price_ = 0;

        address_ = "";

        condition_ = "";

        phoneNumber_ = "";

        email_ = "";

        if (writerBuilder_ == null) {
          writer_ = null;
        } else {
          writer_ = null;
          writerBuilder_ = null;
        }
        if (imagesBuilder_ == null) {
          images_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000200);
        } else {
          imagesBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return GRPCService.PostOuterClass.internal_static_post_PostObj_descriptor;
      }

      @java.lang.Override
      public GRPCService.PostOuterClass.PostObj getDefaultInstanceForType() {
        return GRPCService.PostOuterClass.PostObj.getDefaultInstance();
      }

      @java.lang.Override
      public GRPCService.PostOuterClass.PostObj build() {
        GRPCService.PostOuterClass.PostObj result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public GRPCService.PostOuterClass.PostObj buildPartial() {
        GRPCService.PostOuterClass.PostObj result = new GRPCService.PostOuterClass.PostObj(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.id_ = id_;
        result.title_ = title_;
        result.description_ = description_;
        result.price_ = price_;
        result.address_ = address_;
        result.condition_ = condition_;
        result.phoneNumber_ = phoneNumber_;
        result.email_ = email_;
        if (writerBuilder_ == null) {
          result.writer_ = writer_;
        } else {
          result.writer_ = writerBuilder_.build();
        }
        if (imagesBuilder_ == null) {
          if (((bitField0_ & 0x00000200) == 0x00000200)) {
            images_ = java.util.Collections.unmodifiableList(images_);
            bitField0_ = (bitField0_ & ~0x00000200);
          }
          result.images_ = images_;
        } else {
          result.images_ = imagesBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof GRPCService.PostOuterClass.PostObj) {
          return mergeFrom((GRPCService.PostOuterClass.PostObj)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(GRPCService.PostOuterClass.PostObj other) {
        if (other == GRPCService.PostOuterClass.PostObj.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getTitle().isEmpty()) {
          title_ = other.title_;
          onChanged();
        }
        if (!other.getDescription().isEmpty()) {
          description_ = other.description_;
          onChanged();
        }
        if (other.getPrice() != 0) {
          setPrice(other.getPrice());
        }
        if (!other.getAddress().isEmpty()) {
          address_ = other.address_;
          onChanged();
        }
        if (!other.getCondition().isEmpty()) {
          condition_ = other.condition_;
          onChanged();
        }
        if (!other.getPhoneNumber().isEmpty()) {
          phoneNumber_ = other.phoneNumber_;
          onChanged();
        }
        if (!other.getEmail().isEmpty()) {
          email_ = other.email_;
          onChanged();
        }
        if (other.hasWriter()) {
          mergeWriter(other.getWriter());
        }
        if (imagesBuilder_ == null) {
          if (!other.images_.isEmpty()) {
            if (images_.isEmpty()) {
              images_ = other.images_;
              bitField0_ = (bitField0_ & ~0x00000200);
            } else {
              ensureImagesIsMutable();
              images_.addAll(other.images_);
            }
            onChanged();
          }
        } else {
          if (!other.images_.isEmpty()) {
            if (imagesBuilder_.isEmpty()) {
              imagesBuilder_.dispose();
              imagesBuilder_ = null;
              images_ = other.images_;
              bitField0_ = (bitField0_ & ~0x00000200);
              imagesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getImagesFieldBuilder() : null;
            } else {
              imagesBuilder_.addAllMessages(other.images_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        GRPCService.PostOuterClass.PostObj parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (GRPCService.PostOuterClass.PostObj) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object title_ = "";
      /**
       * <code>string title = 2;</code>
       */
      public java.lang.String getTitle() {
        java.lang.Object ref = title_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          title_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string title = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTitleBytes() {
        java.lang.Object ref = title_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          title_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string title = 2;</code>
       */
      public Builder setTitle(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        title_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string title = 2;</code>
       */
      public Builder clearTitle() {
        
        title_ = getDefaultInstance().getTitle();
        onChanged();
        return this;
      }
      /**
       * <code>string title = 2;</code>
       */
      public Builder setTitleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        title_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object description_ = "";
      /**
       * <code>string description = 3;</code>
       */
      public java.lang.String getDescription() {
        java.lang.Object ref = description_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          description_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string description = 3;</code>
       */
      public com.google.protobuf.ByteString
          getDescriptionBytes() {
        java.lang.Object ref = description_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          description_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string description = 3;</code>
       */
      public Builder setDescription(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        description_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string description = 3;</code>
       */
      public Builder clearDescription() {
        
        description_ = getDefaultInstance().getDescription();
        onChanged();
        return this;
      }
      /**
       * <code>string description = 3;</code>
       */
      public Builder setDescriptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        description_ = value;
        onChanged();
        return this;
      }

      private int price_ ;
      /**
       * <code>int32 price = 4;</code>
       */
      public int getPrice() {
        return price_;
      }
      /**
       * <code>int32 price = 4;</code>
       */
      public Builder setPrice(int value) {
        
        price_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 price = 4;</code>
       */
      public Builder clearPrice() {
        
        price_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object address_ = "";
      /**
       * <code>string address = 5;</code>
       */
      public java.lang.String getAddress() {
        java.lang.Object ref = address_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          address_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string address = 5;</code>
       */
      public com.google.protobuf.ByteString
          getAddressBytes() {
        java.lang.Object ref = address_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          address_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string address = 5;</code>
       */
      public Builder setAddress(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        address_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string address = 5;</code>
       */
      public Builder clearAddress() {
        
        address_ = getDefaultInstance().getAddress();
        onChanged();
        return this;
      }
      /**
       * <code>string address = 5;</code>
       */
      public Builder setAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        address_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object condition_ = "";
      /**
       * <code>string condition = 6;</code>
       */
      public java.lang.String getCondition() {
        java.lang.Object ref = condition_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          condition_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string condition = 6;</code>
       */
      public com.google.protobuf.ByteString
          getConditionBytes() {
        java.lang.Object ref = condition_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          condition_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string condition = 6;</code>
       */
      public Builder setCondition(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        condition_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string condition = 6;</code>
       */
      public Builder clearCondition() {
        
        condition_ = getDefaultInstance().getCondition();
        onChanged();
        return this;
      }
      /**
       * <code>string condition = 6;</code>
       */
      public Builder setConditionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        condition_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object phoneNumber_ = "";
      /**
       * <code>string phoneNumber = 7;</code>
       */
      public java.lang.String getPhoneNumber() {
        java.lang.Object ref = phoneNumber_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          phoneNumber_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string phoneNumber = 7;</code>
       */
      public com.google.protobuf.ByteString
          getPhoneNumberBytes() {
        java.lang.Object ref = phoneNumber_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          phoneNumber_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string phoneNumber = 7;</code>
       */
      public Builder setPhoneNumber(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        phoneNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string phoneNumber = 7;</code>
       */
      public Builder clearPhoneNumber() {
        
        phoneNumber_ = getDefaultInstance().getPhoneNumber();
        onChanged();
        return this;
      }
      /**
       * <code>string phoneNumber = 7;</code>
       */
      public Builder setPhoneNumberBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        phoneNumber_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object email_ = "";
      /**
       * <code>string email = 8;</code>
       */
      public java.lang.String getEmail() {
        java.lang.Object ref = email_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          email_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string email = 8;</code>
       */
      public com.google.protobuf.ByteString
          getEmailBytes() {
        java.lang.Object ref = email_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          email_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string email = 8;</code>
       */
      public Builder setEmail(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        email_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string email = 8;</code>
       */
      public Builder clearEmail() {
        
        email_ = getDefaultInstance().getEmail();
        onChanged();
        return this;
      }
      /**
       * <code>string email = 8;</code>
       */
      public Builder setEmailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        email_ = value;
        onChanged();
        return this;
      }

      private GRPCService.UserOuterClass.UserObj writer_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          GRPCService.UserOuterClass.UserObj, GRPCService.UserOuterClass.UserObj.Builder, GRPCService.UserOuterClass.UserObjOrBuilder> writerBuilder_;
      /**
       * <code>.user.UserObj writer = 9;</code>
       */
      public boolean hasWriter() {
        return writerBuilder_ != null || writer_ != null;
      }
      /**
       * <code>.user.UserObj writer = 9;</code>
       */
      public GRPCService.UserOuterClass.UserObj getWriter() {
        if (writerBuilder_ == null) {
          return writer_ == null ? GRPCService.UserOuterClass.UserObj.getDefaultInstance() : writer_;
        } else {
          return writerBuilder_.getMessage();
        }
      }
      /**
       * <code>.user.UserObj writer = 9;</code>
       */
      public Builder setWriter(GRPCService.UserOuterClass.UserObj value) {
        if (writerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          writer_ = value;
          onChanged();
        } else {
          writerBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.user.UserObj writer = 9;</code>
       */
      public Builder setWriter(
          GRPCService.UserOuterClass.UserObj.Builder builderForValue) {
        if (writerBuilder_ == null) {
          writer_ = builderForValue.build();
          onChanged();
        } else {
          writerBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.user.UserObj writer = 9;</code>
       */
      public Builder mergeWriter(GRPCService.UserOuterClass.UserObj value) {
        if (writerBuilder_ == null) {
          if (writer_ != null) {
            writer_ =
              GRPCService.UserOuterClass.UserObj.newBuilder(writer_).mergeFrom(value).buildPartial();
          } else {
            writer_ = value;
          }
          onChanged();
        } else {
          writerBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.user.UserObj writer = 9;</code>
       */
      public Builder clearWriter() {
        if (writerBuilder_ == null) {
          writer_ = null;
          onChanged();
        } else {
          writer_ = null;
          writerBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.user.UserObj writer = 9;</code>
       */
      public GRPCService.UserOuterClass.UserObj.Builder getWriterBuilder() {
        
        onChanged();
        return getWriterFieldBuilder().getBuilder();
      }
      /**
       * <code>.user.UserObj writer = 9;</code>
       */
      public GRPCService.UserOuterClass.UserObjOrBuilder getWriterOrBuilder() {
        if (writerBuilder_ != null) {
          return writerBuilder_.getMessageOrBuilder();
        } else {
          return writer_ == null ?
              GRPCService.UserOuterClass.UserObj.getDefaultInstance() : writer_;
        }
      }
      /**
       * <code>.user.UserObj writer = 9;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          GRPCService.UserOuterClass.UserObj, GRPCService.UserOuterClass.UserObj.Builder, GRPCService.UserOuterClass.UserObjOrBuilder> 
          getWriterFieldBuilder() {
        if (writerBuilder_ == null) {
          writerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              GRPCService.UserOuterClass.UserObj, GRPCService.UserOuterClass.UserObj.Builder, GRPCService.UserOuterClass.UserObjOrBuilder>(
                  getWriter(),
                  getParentForChildren(),
                  isClean());
          writer_ = null;
        }
        return writerBuilder_;
      }

      private java.util.List<GRPCService.Image.ImageObj> images_ =
        java.util.Collections.emptyList();
      private void ensureImagesIsMutable() {
        if (!((bitField0_ & 0x00000200) == 0x00000200)) {
          images_ = new java.util.ArrayList<GRPCService.Image.ImageObj>(images_);
          bitField0_ |= 0x00000200;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          GRPCService.Image.ImageObj, GRPCService.Image.ImageObj.Builder, GRPCService.Image.ImageObjOrBuilder> imagesBuilder_;

      /**
       * <code>repeated .image.ImageObj images = 10;</code>
       */
      public java.util.List<GRPCService.Image.ImageObj> getImagesList() {
        if (imagesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(images_);
        } else {
          return imagesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .image.ImageObj images = 10;</code>
       */
      public int getImagesCount() {
        if (imagesBuilder_ == null) {
          return images_.size();
        } else {
          return imagesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .image.ImageObj images = 10;</code>
       */
      public GRPCService.Image.ImageObj getImages(int index) {
        if (imagesBuilder_ == null) {
          return images_.get(index);
        } else {
          return imagesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .image.ImageObj images = 10;</code>
       */
      public Builder setImages(
          int index, GRPCService.Image.ImageObj value) {
        if (imagesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureImagesIsMutable();
          images_.set(index, value);
          onChanged();
        } else {
          imagesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .image.ImageObj images = 10;</code>
       */
      public Builder setImages(
          int index, GRPCService.Image.ImageObj.Builder builderForValue) {
        if (imagesBuilder_ == null) {
          ensureImagesIsMutable();
          images_.set(index, builderForValue.build());
          onChanged();
        } else {
          imagesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .image.ImageObj images = 10;</code>
       */
      public Builder addImages(GRPCService.Image.ImageObj value) {
        if (imagesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureImagesIsMutable();
          images_.add(value);
          onChanged();
        } else {
          imagesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .image.ImageObj images = 10;</code>
       */
      public Builder addImages(
          int index, GRPCService.Image.ImageObj value) {
        if (imagesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureImagesIsMutable();
          images_.add(index, value);
          onChanged();
        } else {
          imagesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .image.ImageObj images = 10;</code>
       */
      public Builder addImages(
          GRPCService.Image.ImageObj.Builder builderForValue) {
        if (imagesBuilder_ == null) {
          ensureImagesIsMutable();
          images_.add(builderForValue.build());
          onChanged();
        } else {
          imagesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .image.ImageObj images = 10;</code>
       */
      public Builder addImages(
          int index, GRPCService.Image.ImageObj.Builder builderForValue) {
        if (imagesBuilder_ == null) {
          ensureImagesIsMutable();
          images_.add(index, builderForValue.build());
          onChanged();
        } else {
          imagesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .image.ImageObj images = 10;</code>
       */
      public Builder addAllImages(
          java.lang.Iterable<? extends GRPCService.Image.ImageObj> values) {
        if (imagesBuilder_ == null) {
          ensureImagesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, images_);
          onChanged();
        } else {
          imagesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .image.ImageObj images = 10;</code>
       */
      public Builder clearImages() {
        if (imagesBuilder_ == null) {
          images_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000200);
          onChanged();
        } else {
          imagesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .image.ImageObj images = 10;</code>
       */
      public Builder removeImages(int index) {
        if (imagesBuilder_ == null) {
          ensureImagesIsMutable();
          images_.remove(index);
          onChanged();
        } else {
          imagesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .image.ImageObj images = 10;</code>
       */
      public GRPCService.Image.ImageObj.Builder getImagesBuilder(
          int index) {
        return getImagesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .image.ImageObj images = 10;</code>
       */
      public GRPCService.Image.ImageObjOrBuilder getImagesOrBuilder(
          int index) {
        if (imagesBuilder_ == null) {
          return images_.get(index);  } else {
          return imagesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .image.ImageObj images = 10;</code>
       */
      public java.util.List<? extends GRPCService.Image.ImageObjOrBuilder> 
           getImagesOrBuilderList() {
        if (imagesBuilder_ != null) {
          return imagesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(images_);
        }
      }
      /**
       * <code>repeated .image.ImageObj images = 10;</code>
       */
      public GRPCService.Image.ImageObj.Builder addImagesBuilder() {
        return getImagesFieldBuilder().addBuilder(
            GRPCService.Image.ImageObj.getDefaultInstance());
      }
      /**
       * <code>repeated .image.ImageObj images = 10;</code>
       */
      public GRPCService.Image.ImageObj.Builder addImagesBuilder(
          int index) {
        return getImagesFieldBuilder().addBuilder(
            index, GRPCService.Image.ImageObj.getDefaultInstance());
      }
      /**
       * <code>repeated .image.ImageObj images = 10;</code>
       */
      public java.util.List<GRPCService.Image.ImageObj.Builder> 
           getImagesBuilderList() {
        return getImagesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          GRPCService.Image.ImageObj, GRPCService.Image.ImageObj.Builder, GRPCService.Image.ImageObjOrBuilder> 
          getImagesFieldBuilder() {
        if (imagesBuilder_ == null) {
          imagesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              GRPCService.Image.ImageObj, GRPCService.Image.ImageObj.Builder, GRPCService.Image.ImageObjOrBuilder>(
                  images_,
                  ((bitField0_ & 0x00000200) == 0x00000200),
                  getParentForChildren(),
                  isClean());
          images_ = null;
        }
        return imagesBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:post.PostObj)
    }

    // @@protoc_insertion_point(class_scope:post.PostObj)
    private static final GRPCService.PostOuterClass.PostObj DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new GRPCService.PostOuterClass.PostObj();
    }

    public static GRPCService.PostOuterClass.PostObj getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PostObj>
        PARSER = new com.google.protobuf.AbstractParser<PostObj>() {
      @java.lang.Override
      public PostObj parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PostObj(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PostObj> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PostObj> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public GRPCService.PostOuterClass.PostObj getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface dateCreatedOrBuilder extends
      // @@protoc_insertion_point(interface_extends:post.dateCreated)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 day = 1;</code>
     */
    int getDay();

    /**
     * <code>int32 month = 2;</code>
     */
    int getMonth();

    /**
     * <code>int32 year = 3;</code>
     */
    int getYear();
  }
  /**
   * Protobuf type {@code post.dateCreated}
   */
  public  static final class dateCreated extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:post.dateCreated)
      dateCreatedOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use dateCreated.newBuilder() to construct.
    private dateCreated(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private dateCreated() {
      day_ = 0;
      month_ = 0;
      year_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private dateCreated(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              day_ = input.readInt32();
              break;
            }
            case 16: {

              month_ = input.readInt32();
              break;
            }
            case 24: {

              year_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return GRPCService.PostOuterClass.internal_static_post_dateCreated_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return GRPCService.PostOuterClass.internal_static_post_dateCreated_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              GRPCService.PostOuterClass.dateCreated.class, GRPCService.PostOuterClass.dateCreated.Builder.class);
    }

    public static final int DAY_FIELD_NUMBER = 1;
    private int day_;
    /**
     * <code>int32 day = 1;</code>
     */
    public int getDay() {
      return day_;
    }

    public static final int MONTH_FIELD_NUMBER = 2;
    private int month_;
    /**
     * <code>int32 month = 2;</code>
     */
    public int getMonth() {
      return month_;
    }

    public static final int YEAR_FIELD_NUMBER = 3;
    private int year_;
    /**
     * <code>int32 year = 3;</code>
     */
    public int getYear() {
      return year_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (day_ != 0) {
        output.writeInt32(1, day_);
      }
      if (month_ != 0) {
        output.writeInt32(2, month_);
      }
      if (year_ != 0) {
        output.writeInt32(3, year_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (day_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, day_);
      }
      if (month_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, month_);
      }
      if (year_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, year_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof GRPCService.PostOuterClass.dateCreated)) {
        return super.equals(obj);
      }
      GRPCService.PostOuterClass.dateCreated other = (GRPCService.PostOuterClass.dateCreated) obj;

      boolean result = true;
      result = result && (getDay()
          == other.getDay());
      result = result && (getMonth()
          == other.getMonth());
      result = result && (getYear()
          == other.getYear());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DAY_FIELD_NUMBER;
      hash = (53 * hash) + getDay();
      hash = (37 * hash) + MONTH_FIELD_NUMBER;
      hash = (53 * hash) + getMonth();
      hash = (37 * hash) + YEAR_FIELD_NUMBER;
      hash = (53 * hash) + getYear();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static GRPCService.PostOuterClass.dateCreated parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GRPCService.PostOuterClass.dateCreated parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GRPCService.PostOuterClass.dateCreated parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GRPCService.PostOuterClass.dateCreated parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GRPCService.PostOuterClass.dateCreated parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GRPCService.PostOuterClass.dateCreated parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GRPCService.PostOuterClass.dateCreated parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GRPCService.PostOuterClass.dateCreated parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static GRPCService.PostOuterClass.dateCreated parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static GRPCService.PostOuterClass.dateCreated parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static GRPCService.PostOuterClass.dateCreated parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GRPCService.PostOuterClass.dateCreated parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(GRPCService.PostOuterClass.dateCreated prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code post.dateCreated}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:post.dateCreated)
        GRPCService.PostOuterClass.dateCreatedOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return GRPCService.PostOuterClass.internal_static_post_dateCreated_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return GRPCService.PostOuterClass.internal_static_post_dateCreated_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                GRPCService.PostOuterClass.dateCreated.class, GRPCService.PostOuterClass.dateCreated.Builder.class);
      }

      // Construct using GRPCService.PostOuterClass.dateCreated.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        day_ = 0;

        month_ = 0;

        year_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return GRPCService.PostOuterClass.internal_static_post_dateCreated_descriptor;
      }

      @java.lang.Override
      public GRPCService.PostOuterClass.dateCreated getDefaultInstanceForType() {
        return GRPCService.PostOuterClass.dateCreated.getDefaultInstance();
      }

      @java.lang.Override
      public GRPCService.PostOuterClass.dateCreated build() {
        GRPCService.PostOuterClass.dateCreated result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public GRPCService.PostOuterClass.dateCreated buildPartial() {
        GRPCService.PostOuterClass.dateCreated result = new GRPCService.PostOuterClass.dateCreated(this);
        result.day_ = day_;
        result.month_ = month_;
        result.year_ = year_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof GRPCService.PostOuterClass.dateCreated) {
          return mergeFrom((GRPCService.PostOuterClass.dateCreated)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(GRPCService.PostOuterClass.dateCreated other) {
        if (other == GRPCService.PostOuterClass.dateCreated.getDefaultInstance()) return this;
        if (other.getDay() != 0) {
          setDay(other.getDay());
        }
        if (other.getMonth() != 0) {
          setMonth(other.getMonth());
        }
        if (other.getYear() != 0) {
          setYear(other.getYear());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        GRPCService.PostOuterClass.dateCreated parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (GRPCService.PostOuterClass.dateCreated) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int day_ ;
      /**
       * <code>int32 day = 1;</code>
       */
      public int getDay() {
        return day_;
      }
      /**
       * <code>int32 day = 1;</code>
       */
      public Builder setDay(int value) {
        
        day_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 day = 1;</code>
       */
      public Builder clearDay() {
        
        day_ = 0;
        onChanged();
        return this;
      }

      private int month_ ;
      /**
       * <code>int32 month = 2;</code>
       */
      public int getMonth() {
        return month_;
      }
      /**
       * <code>int32 month = 2;</code>
       */
      public Builder setMonth(int value) {
        
        month_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 month = 2;</code>
       */
      public Builder clearMonth() {
        
        month_ = 0;
        onChanged();
        return this;
      }

      private int year_ ;
      /**
       * <code>int32 year = 3;</code>
       */
      public int getYear() {
        return year_;
      }
      /**
       * <code>int32 year = 3;</code>
       */
      public Builder setYear(int value) {
        
        year_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 year = 3;</code>
       */
      public Builder clearYear() {
        
        year_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:post.dateCreated)
    }

    // @@protoc_insertion_point(class_scope:post.dateCreated)
    private static final GRPCService.PostOuterClass.dateCreated DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new GRPCService.PostOuterClass.dateCreated();
    }

    public static GRPCService.PostOuterClass.dateCreated getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<dateCreated>
        PARSER = new com.google.protobuf.AbstractParser<dateCreated>() {
      @java.lang.Override
      public dateCreated parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new dateCreated(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<dateCreated> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<dateCreated> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public GRPCService.PostOuterClass.dateCreated getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_post_PostObj_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_post_PostObj_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_post_dateCreated_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_post_dateCreated_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\npost.proto\022\004post\032\nuser.proto\032\013image.pr" +
      "oto\"\320\001\n\007PostObj\022\n\n\002id\030\001 \001(\005\022\r\n\005title\030\002 \001" +
      "(\t\022\023\n\013description\030\003 \001(\t\022\r\n\005price\030\004 \001(\005\022\017" +
      "\n\007address\030\005 \001(\t\022\021\n\tcondition\030\006 \001(\t\022\023\n\013ph" +
      "oneNumber\030\007 \001(\t\022\r\n\005email\030\010 \001(\t\022\035\n\006writer" +
      "\030\t \001(\0132\r.user.UserObj\022\037\n\006images\030\n \003(\0132\017." +
      "image.ImageObj\"7\n\013dateCreated\022\013\n\003day\030\001 \001" +
      "(\005\022\r\n\005month\030\002 \001(\005\022\014\n\004year\030\003 \001(\0052\006\n\004PostB" +
      "\r\n\013GRPCServiceb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          GRPCService.UserOuterClass.getDescriptor(),
          GRPCService.Image.getDescriptor(),
        }, assigner);
    internal_static_post_PostObj_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_post_PostObj_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_post_PostObj_descriptor,
        new java.lang.String[] { "Id", "Title", "Description", "Price", "Address", "Condition", "PhoneNumber", "Email", "Writer", "Images", });
    internal_static_post_dateCreated_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_post_dateCreated_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_post_dateCreated_descriptor,
        new java.lang.String[] { "Day", "Month", "Year", });
    GRPCService.UserOuterClass.getDescriptor();
    GRPCService.Image.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
