// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: subcategory.proto

package GRPCService;

public final class Subcategory {
  private Subcategory() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SubcategoryObjOrBuilder extends
      // @@protoc_insertion_point(interface_extends:subcategory.SubcategoryObj)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>repeated .post.PostObj posts = 3;</code>
     */
    java.util.List<GRPCService.PostOuterClass.PostObj> 
        getPostsList();
    /**
     * <code>repeated .post.PostObj posts = 3;</code>
     */
    GRPCService.PostOuterClass.PostObj getPosts(int index);
    /**
     * <code>repeated .post.PostObj posts = 3;</code>
     */
    int getPostsCount();
    /**
     * <code>repeated .post.PostObj posts = 3;</code>
     */
    java.util.List<? extends GRPCService.PostOuterClass.PostObjOrBuilder> 
        getPostsOrBuilderList();
    /**
     * <code>repeated .post.PostObj posts = 3;</code>
     */
    GRPCService.PostOuterClass.PostObjOrBuilder getPostsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code subcategory.SubcategoryObj}
   */
  public  static final class SubcategoryObj extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:subcategory.SubcategoryObj)
      SubcategoryObjOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SubcategoryObj.newBuilder() to construct.
    private SubcategoryObj(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SubcategoryObj() {
      id_ = 0;
      name_ = "";
      posts_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SubcategoryObj(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                posts_ = new java.util.ArrayList<GRPCService.PostOuterClass.PostObj>();
                mutable_bitField0_ |= 0x00000004;
              }
              posts_.add(
                  input.readMessage(GRPCService.PostOuterClass.PostObj.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          posts_ = java.util.Collections.unmodifiableList(posts_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return GRPCService.Subcategory.internal_static_subcategory_SubcategoryObj_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return GRPCService.Subcategory.internal_static_subcategory_SubcategoryObj_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              GRPCService.Subcategory.SubcategoryObj.class, GRPCService.Subcategory.SubcategoryObj.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int POSTS_FIELD_NUMBER = 3;
    private java.util.List<GRPCService.PostOuterClass.PostObj> posts_;
    /**
     * <code>repeated .post.PostObj posts = 3;</code>
     */
    public java.util.List<GRPCService.PostOuterClass.PostObj> getPostsList() {
      return posts_;
    }
    /**
     * <code>repeated .post.PostObj posts = 3;</code>
     */
    public java.util.List<? extends GRPCService.PostOuterClass.PostObjOrBuilder> 
        getPostsOrBuilderList() {
      return posts_;
    }
    /**
     * <code>repeated .post.PostObj posts = 3;</code>
     */
    public int getPostsCount() {
      return posts_.size();
    }
    /**
     * <code>repeated .post.PostObj posts = 3;</code>
     */
    public GRPCService.PostOuterClass.PostObj getPosts(int index) {
      return posts_.get(index);
    }
    /**
     * <code>repeated .post.PostObj posts = 3;</code>
     */
    public GRPCService.PostOuterClass.PostObjOrBuilder getPostsOrBuilder(
        int index) {
      return posts_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      for (int i = 0; i < posts_.size(); i++) {
        output.writeMessage(3, posts_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      for (int i = 0; i < posts_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, posts_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof GRPCService.Subcategory.SubcategoryObj)) {
        return super.equals(obj);
      }
      GRPCService.Subcategory.SubcategoryObj other = (GRPCService.Subcategory.SubcategoryObj) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && getName()
          .equals(other.getName());
      result = result && getPostsList()
          .equals(other.getPostsList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      if (getPostsCount() > 0) {
        hash = (37 * hash) + POSTS_FIELD_NUMBER;
        hash = (53 * hash) + getPostsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static GRPCService.Subcategory.SubcategoryObj parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GRPCService.Subcategory.SubcategoryObj parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GRPCService.Subcategory.SubcategoryObj parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GRPCService.Subcategory.SubcategoryObj parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GRPCService.Subcategory.SubcategoryObj parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GRPCService.Subcategory.SubcategoryObj parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GRPCService.Subcategory.SubcategoryObj parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GRPCService.Subcategory.SubcategoryObj parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static GRPCService.Subcategory.SubcategoryObj parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static GRPCService.Subcategory.SubcategoryObj parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static GRPCService.Subcategory.SubcategoryObj parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GRPCService.Subcategory.SubcategoryObj parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(GRPCService.Subcategory.SubcategoryObj prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code subcategory.SubcategoryObj}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:subcategory.SubcategoryObj)
        GRPCService.Subcategory.SubcategoryObjOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return GRPCService.Subcategory.internal_static_subcategory_SubcategoryObj_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return GRPCService.Subcategory.internal_static_subcategory_SubcategoryObj_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                GRPCService.Subcategory.SubcategoryObj.class, GRPCService.Subcategory.SubcategoryObj.Builder.class);
      }

      // Construct using GRPCService.Subcategory.SubcategoryObj.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getPostsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        name_ = "";

        if (postsBuilder_ == null) {
          posts_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          postsBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return GRPCService.Subcategory.internal_static_subcategory_SubcategoryObj_descriptor;
      }

      @java.lang.Override
      public GRPCService.Subcategory.SubcategoryObj getDefaultInstanceForType() {
        return GRPCService.Subcategory.SubcategoryObj.getDefaultInstance();
      }

      @java.lang.Override
      public GRPCService.Subcategory.SubcategoryObj build() {
        GRPCService.Subcategory.SubcategoryObj result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public GRPCService.Subcategory.SubcategoryObj buildPartial() {
        GRPCService.Subcategory.SubcategoryObj result = new GRPCService.Subcategory.SubcategoryObj(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.id_ = id_;
        result.name_ = name_;
        if (postsBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            posts_ = java.util.Collections.unmodifiableList(posts_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.posts_ = posts_;
        } else {
          result.posts_ = postsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof GRPCService.Subcategory.SubcategoryObj) {
          return mergeFrom((GRPCService.Subcategory.SubcategoryObj)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(GRPCService.Subcategory.SubcategoryObj other) {
        if (other == GRPCService.Subcategory.SubcategoryObj.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (postsBuilder_ == null) {
          if (!other.posts_.isEmpty()) {
            if (posts_.isEmpty()) {
              posts_ = other.posts_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensurePostsIsMutable();
              posts_.addAll(other.posts_);
            }
            onChanged();
          }
        } else {
          if (!other.posts_.isEmpty()) {
            if (postsBuilder_.isEmpty()) {
              postsBuilder_.dispose();
              postsBuilder_ = null;
              posts_ = other.posts_;
              bitField0_ = (bitField0_ & ~0x00000004);
              postsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getPostsFieldBuilder() : null;
            } else {
              postsBuilder_.addAllMessages(other.posts_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        GRPCService.Subcategory.SubcategoryObj parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (GRPCService.Subcategory.SubcategoryObj) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.util.List<GRPCService.PostOuterClass.PostObj> posts_ =
        java.util.Collections.emptyList();
      private void ensurePostsIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          posts_ = new java.util.ArrayList<GRPCService.PostOuterClass.PostObj>(posts_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          GRPCService.PostOuterClass.PostObj, GRPCService.PostOuterClass.PostObj.Builder, GRPCService.PostOuterClass.PostObjOrBuilder> postsBuilder_;

      /**
       * <code>repeated .post.PostObj posts = 3;</code>
       */
      public java.util.List<GRPCService.PostOuterClass.PostObj> getPostsList() {
        if (postsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(posts_);
        } else {
          return postsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .post.PostObj posts = 3;</code>
       */
      public int getPostsCount() {
        if (postsBuilder_ == null) {
          return posts_.size();
        } else {
          return postsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .post.PostObj posts = 3;</code>
       */
      public GRPCService.PostOuterClass.PostObj getPosts(int index) {
        if (postsBuilder_ == null) {
          return posts_.get(index);
        } else {
          return postsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .post.PostObj posts = 3;</code>
       */
      public Builder setPosts(
          int index, GRPCService.PostOuterClass.PostObj value) {
        if (postsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePostsIsMutable();
          posts_.set(index, value);
          onChanged();
        } else {
          postsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .post.PostObj posts = 3;</code>
       */
      public Builder setPosts(
          int index, GRPCService.PostOuterClass.PostObj.Builder builderForValue) {
        if (postsBuilder_ == null) {
          ensurePostsIsMutable();
          posts_.set(index, builderForValue.build());
          onChanged();
        } else {
          postsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .post.PostObj posts = 3;</code>
       */
      public Builder addPosts(GRPCService.PostOuterClass.PostObj value) {
        if (postsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePostsIsMutable();
          posts_.add(value);
          onChanged();
        } else {
          postsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .post.PostObj posts = 3;</code>
       */
      public Builder addPosts(
          int index, GRPCService.PostOuterClass.PostObj value) {
        if (postsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePostsIsMutable();
          posts_.add(index, value);
          onChanged();
        } else {
          postsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .post.PostObj posts = 3;</code>
       */
      public Builder addPosts(
          GRPCService.PostOuterClass.PostObj.Builder builderForValue) {
        if (postsBuilder_ == null) {
          ensurePostsIsMutable();
          posts_.add(builderForValue.build());
          onChanged();
        } else {
          postsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .post.PostObj posts = 3;</code>
       */
      public Builder addPosts(
          int index, GRPCService.PostOuterClass.PostObj.Builder builderForValue) {
        if (postsBuilder_ == null) {
          ensurePostsIsMutable();
          posts_.add(index, builderForValue.build());
          onChanged();
        } else {
          postsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .post.PostObj posts = 3;</code>
       */
      public Builder addAllPosts(
          java.lang.Iterable<? extends GRPCService.PostOuterClass.PostObj> values) {
        if (postsBuilder_ == null) {
          ensurePostsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, posts_);
          onChanged();
        } else {
          postsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .post.PostObj posts = 3;</code>
       */
      public Builder clearPosts() {
        if (postsBuilder_ == null) {
          posts_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          postsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .post.PostObj posts = 3;</code>
       */
      public Builder removePosts(int index) {
        if (postsBuilder_ == null) {
          ensurePostsIsMutable();
          posts_.remove(index);
          onChanged();
        } else {
          postsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .post.PostObj posts = 3;</code>
       */
      public GRPCService.PostOuterClass.PostObj.Builder getPostsBuilder(
          int index) {
        return getPostsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .post.PostObj posts = 3;</code>
       */
      public GRPCService.PostOuterClass.PostObjOrBuilder getPostsOrBuilder(
          int index) {
        if (postsBuilder_ == null) {
          return posts_.get(index);  } else {
          return postsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .post.PostObj posts = 3;</code>
       */
      public java.util.List<? extends GRPCService.PostOuterClass.PostObjOrBuilder> 
           getPostsOrBuilderList() {
        if (postsBuilder_ != null) {
          return postsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(posts_);
        }
      }
      /**
       * <code>repeated .post.PostObj posts = 3;</code>
       */
      public GRPCService.PostOuterClass.PostObj.Builder addPostsBuilder() {
        return getPostsFieldBuilder().addBuilder(
            GRPCService.PostOuterClass.PostObj.getDefaultInstance());
      }
      /**
       * <code>repeated .post.PostObj posts = 3;</code>
       */
      public GRPCService.PostOuterClass.PostObj.Builder addPostsBuilder(
          int index) {
        return getPostsFieldBuilder().addBuilder(
            index, GRPCService.PostOuterClass.PostObj.getDefaultInstance());
      }
      /**
       * <code>repeated .post.PostObj posts = 3;</code>
       */
      public java.util.List<GRPCService.PostOuterClass.PostObj.Builder> 
           getPostsBuilderList() {
        return getPostsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          GRPCService.PostOuterClass.PostObj, GRPCService.PostOuterClass.PostObj.Builder, GRPCService.PostOuterClass.PostObjOrBuilder> 
          getPostsFieldBuilder() {
        if (postsBuilder_ == null) {
          postsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              GRPCService.PostOuterClass.PostObj, GRPCService.PostOuterClass.PostObj.Builder, GRPCService.PostOuterClass.PostObjOrBuilder>(
                  posts_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          posts_ = null;
        }
        return postsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:subcategory.SubcategoryObj)
    }

    // @@protoc_insertion_point(class_scope:subcategory.SubcategoryObj)
    private static final GRPCService.Subcategory.SubcategoryObj DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new GRPCService.Subcategory.SubcategoryObj();
    }

    public static GRPCService.Subcategory.SubcategoryObj getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SubcategoryObj>
        PARSER = new com.google.protobuf.AbstractParser<SubcategoryObj>() {
      @java.lang.Override
      public SubcategoryObj parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SubcategoryObj(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SubcategoryObj> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SubcategoryObj> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public GRPCService.Subcategory.SubcategoryObj getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_subcategory_SubcategoryObj_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_subcategory_SubcategoryObj_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021subcategory.proto\022\013subcategory\032\nuser.p" +
      "roto\032\npost.proto\"H\n\016SubcategoryObj\022\n\n\002id" +
      "\030\001 \001(\005\022\014\n\004name\030\002 \001(\t\022\034\n\005posts\030\003 \003(\0132\r.po" +
      "st.PostObj2\r\n\013subCategoryB\r\n\013GRPCService" +
      "b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          GRPCService.UserOuterClass.getDescriptor(),
          GRPCService.PostOuterClass.getDescriptor(),
        }, assigner);
    internal_static_subcategory_SubcategoryObj_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_subcategory_SubcategoryObj_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_subcategory_SubcategoryObj_descriptor,
        new java.lang.String[] { "Id", "Name", "Posts", });
    GRPCService.UserOuterClass.getDescriptor();
    GRPCService.PostOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
